"""Compatibility re-exports for the split balance workbook implementation.

The workbook builders now live under `backend.app.core_finance.balance_workbook`.
Keep this legacy module path stable because services and tests import it directly.
"""
from __future__ import annotations

from backend.app.core_finance.balance_workbook._analysis_tables import (
    _build_campisi_table,
    _build_counterparty_type_table,
    _build_cross_analysis_table,
    _build_currency_split_table,
    _build_decision_items_table,
    _build_event_calendar_table,
    _build_industry_table,
    _build_interest_mode_table,
    _build_rate_distribution_table,
    _build_rating_table,
)
from backend.app.core_finance.balance_workbook._bond_tables import (
    _build_bond_business_type_table,
    _build_cards,
    _build_cashflow_calendar_table,
    _build_customer_attribute_analysis_table,
    _build_issuance_business_type_table,
    _build_issuer_concentration_table,
    _build_liquidity_layers_table,
    _build_maturity_gap_table,
    _build_portfolio_comparison_table,
    _build_vintage_analysis_table,
)
from backend.app.core_finance.balance_workbook._ifrs9_tables import (
    _build_account_category_comparison_table,
    _build_ifrs9_classification_table,
    _build_ifrs9_position_scope_table,
    _build_ifrs9_source_family_table,
    _build_rule_reference_table,
)
from backend.app.core_finance.balance_workbook._risk_tables import (
    _build_overdue_credit_quality_detail_table,
    _build_overdue_credit_quality_rating_table,
    _build_regulatory_limits_table,
    _build_risk_alerts_table,
)
from backend.app.core_finance.balance_workbook._utils import (
    _card,
    _decimal_value,
    _group_rows,
    _match_bucket,
    _merged_weighted_average,
    _month_key,
    _month_key_from_index,
    _month_ladder,
    _normalize_interest_mode,
    _optional_remaining_years,
    _rate_value,
    _remaining_years,
    _safe_ratio,
    _section,
    _severity_from_gap,
    _spread_bp,
    _sum_decimal,
    _table,
    _to_wanyuan,
    _weighted_average,
)
from backend.app.core_finance.balance_workbook.builder import (
    build_balance_analysis_workbook_payload,
)

__all__ = [
    "build_balance_analysis_workbook_payload",
    "_build_account_category_comparison_table",
    "_build_bond_business_type_table",
    "_build_campisi_table",
    "_build_cards",
    "_build_cashflow_calendar_table",
    "_build_counterparty_type_table",
    "_build_cross_analysis_table",
    "_build_currency_split_table",
    "_build_customer_attribute_analysis_table",
    "_build_decision_items_table",
    "_build_event_calendar_table",
    "_build_ifrs9_classification_table",
    "_build_ifrs9_position_scope_table",
    "_build_ifrs9_source_family_table",
    "_build_industry_table",
    "_build_interest_mode_table",
    "_build_issuance_business_type_table",
    "_build_issuer_concentration_table",
    "_build_liquidity_layers_table",
    "_build_maturity_gap_table",
    "_build_overdue_credit_quality_detail_table",
    "_build_overdue_credit_quality_rating_table",
    "_build_portfolio_comparison_table",
    "_build_rate_distribution_table",
    "_build_rating_table",
    "_build_regulatory_limits_table",
    "_build_risk_alerts_table",
    "_build_rule_reference_table",
    "_build_vintage_analysis_table",
    "_card",
    "_decimal_value",
    "_group_rows",
    "_match_bucket",
    "_merged_weighted_average",
    "_month_key",
    "_month_key_from_index",
    "_month_ladder",
    "_normalize_interest_mode",
    "_optional_remaining_years",
    "_rate_value",
    "_remaining_years",
    "_safe_ratio",
    "_section",
    "_severity_from_gap",
    "_spread_bp",
    "_sum_decimal",
    "_table",
    "_to_wanyuan",
    "_weighted_average",
]
