import { render, screen, within } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import type { LivermoreStrategyPayload } from "../../../api/contracts";
import { MarketDataLivermoreBusinessDetail } from "./MarketDataLivermoreBusinessDetail";

function buildPayload(): LivermoreStrategyPayload {
  return {
    as_of_date: "2026-07-28",
    requested_as_of_date: "2026-07-29",
    strategy_name: "Livermore A-Share Defended Trend",
    basis: "analytical",
    market_gate: {
      state: "WARM",
      exposure: 0.6,
      passed_conditions: 3,
      available_conditions: 4,
      required_conditions: 3,
      conditions: [
        {
          key: "csi300_close_gt_ma60",
          label: "CSI300 close > MA60",
          status: "pass",
          evidence: "Close is above MA60.",
          source_series_id: "CA.CSI300",
        },
      ],
    },
    rule_readiness: [
      {
        key: "market_gate",
        title: "Market gate",
        status: "ready",
        summary: "Market gate inputs are landed.",
        required_inputs: ["broad_index_history", "breadth"],
        missing_inputs: [],
      },
    ],
    diagnostics: [
      {
        severity: "warning",
        code: "LIVERMORE_INPUT_FRESHNESS_DEGRADED",
        message: "Breadth input lagged 2 days.",
        input_family: "breadth",
      },
    ],
    data_gaps: [
      {
        input_family: "breadth",
        status: "stale",
        evidence: "Breadth snapshot is two days old.",
        input: "breadth_close",
        business_date: "2026-07-26",
        age_days: 2,
        tier: "stale",
      },
    ],
    supported_outputs: [
      "market_gate",
      "sector_rank",
      "stock_candidates",
      "uptrend_momentum_candidates",
      "fresh_trend_watchlist",
      "factor_screen_candidates",
      "theme_breakout",
      "hybrid_fusion",
      "risk_exit",
    ],
    unsupported_outputs: [
      {
        key: "mean_reversion_candidates",
        reason: "Mean reversion watchlist is paused when the market gate is HOT or OVERHEAT.",
      },
    ],
    module_states: [
      {
        key: "market_gate",
        state: "ready",
        render_mode: "primary",
        source_date: "2026-07-28",
        lag_days: 0,
        threshold_days: 3,
        reasons: [],
        evidence_scope: "primary",
        excludes_from_primary: false,
      },
      {
        key: "hybrid_fusion",
        state: "ready",
        render_mode: "evidence_only",
        source_date: "2026-07-28",
        lag_days: 0,
        threshold_days: 3,
        reasons: [],
        evidence_scope: "detail",
        excludes_from_primary: false,
      },
    ],
    cycle_rotation_framework: {
      strategy_name: "A-share cycle rotation research framework",
      display_name: "A股景气周期选股与行业轮动",
      observation_only: true,
      implementation_stage: "verification_pending",
      score_formula: "CycleScore = weighted evidence",
      macro_formula: "Macro layer weighted breadth and spread evidence.",
      fusion_formula: "Fusion action resolves cycle and life conflicts.",
      rebalance_cadence: "Monthly core review",
      fusion_policy: {
        cycle_weight: 0.55,
        life_weight: 0.45,
        conflict_policy: "Cycle wins unless life overlay blocks.",
        matrix: [
          { cycle: "warm", life: "confirm", action: "review" },
        ],
      },
      macro_layer: {
        macro_score: 0.73,
        ready: true,
        evidence: "Macro breadth and spreads aligned.",
        available_inputs: ["breadth", "credit_spread"],
        missing_inputs: [],
        lineage: { breadth: "fact_breadth_daily" },
      },
      lifecourt_overlay: {
        display_name: "Life Court overlay",
        observation_only: true,
        implementation_stage: "proxy_only",
        rebalance_cadence: "Weekly",
        boundary: "observation-only",
        available_inputs: ["trend", "factor"],
        missing_inputs: [],
        life_long_gates: ["trend_ok"],
      },
      layers: [
        {
          key: "macro_direction",
          title: "Macro direction",
          weight: 0.3,
          status: "ready",
          evidence: "Breadth positive and spreads stable.",
          available_inputs: ["breadth", "spread"],
          missing_inputs: [],
        },
      ],
      constraints: ["Observation only"],
      boundary: "observation-only",
    },
    sector_rank: {
      as_of_date: "2026-07-28",
      formula_version: "rv_livermore_sector_strength_observation_v1",
      is_provisional: false,
      formula_status: "signed_off",
      formula_note: "Sector strength rank is observation-only.",
      sector_count: 1,
      excluded_constituent_count: 0,
      excluded_sector_count: 0,
      leader_constituent_limit: 2,
      leader_constituent_method: "top_turn_same_day",
      items: [
        {
          rank: 1,
          sector_code: "801001",
          sector_name: "AI",
          score: 0.93,
          avg_pctchange: 4.2,
          avg_turn: 2.6,
          avg_amplitude: 3.1,
          constituent_count: 12,
          leader_constituents: [
            {
              rank: 1,
              stock_code: "688001.SH",
              stock_name: "Alpha AI",
              pctchange: 9.8,
              turn: 5.4,
              amplitude: 6.1,
            },
          ],
        },
      ],
    },
    stock_candidates: {
      as_of_date: "2026-07-28",
      formula_version: "rv_stock_candidates_v2",
      market_state: "WARM",
      input_stock_count: 1200,
      candidate_count: 1,
      excluded_stock_count: 4,
      insufficient_history_count: 1,
      selection_policy: "exp3b",
      fundamental_overlay: {
        status: "ready",
        input_candidate_count: 6,
        factor_missing_count: 0,
      },
      items: [
        {
          rank: 1,
          stock_code: "688001.SH",
          stock_name: "Alpha AI",
          sector_code: "801001",
          sector_name: "AI",
          sector_rank: 1,
          close: 21.45,
          breakout_level: 20.9,
          ema10: 20.8,
          ma20: 19.5,
          ma60: 17.2,
          ma120: 15.8,
          close_strength: 0.81,
          gap_norm: 0.04,
          breakout_extension_norm: 0.02,
          abnormal_turnover: 1.4,
          factor_score: 0.88,
          factor_overlay_rank: 2,
          pe: 24.1,
          pb: 3.8,
          ps: 5.5,
          roe: 0.16,
          gross_margin: 0.37,
          three_month_return: 0.22,
          twelve_month_return: 0.64,
          volatility: 0.31,
          dividend_yield: 0.01,
        },
      ],
    },
    uptrend_momentum_candidates: {
      as_of_date: "2026-07-28",
      formula_version: "rv_uptrend_momentum_candidates_v1",
      market_state: "WARM",
      observation_only: true,
      input_stock_count: 990,
      candidate_count: 1,
      excluded_stock_count: 12,
      insufficient_history_count: 0,
      items: [
        {
          rank: 1,
          stock_code: "300750.SZ",
          stock_name: "Momentum Core",
          sector_code: "801002",
          sector_name: "Battery",
          close: 42.8,
          ma20: 39.2,
          ma60: 35.6,
          ma120: 31.5,
          return_20d: 0.11,
          return_60d: 0.26,
          return_120d: 0.47,
          close_to_ma20: 0.09,
          amount_ratio: 1.34,
          pctchange: 3.6,
          turn: 4.1,
          amplitude: 5.2,
          score: 0.91,
        },
      ],
    },
    fresh_trend_watchlist: {
      as_of_date: "2026-07-28",
      formula_version: "rv_fresh_trend_watchlist_candidates_v1",
      market_state: "WARM",
      observation_only: true,
      input_stock_count: 850,
      candidate_count: 1,
      excluded_stock_count: 10,
      insufficient_history_count: 0,
      items: [
        {
          rank: 1,
          stock_code: "002594.SZ",
          stock_name: "Fresh Trend",
          sector_code: "801003",
          sector_name: "Auto",
          concepts: ["EV", "Export"],
          close: 33.7,
          ma20: 31.2,
          ma60: 28.8,
          ma120: 24.9,
          return_20d: 0.08,
          return_60d: 0.19,
          return_120d: 0.39,
          close_to_ma20: 0.06,
          amount_ratio: 1.22,
          pctchange: 2.9,
          turn: 3.3,
          amplitude: 4.4,
          hlimitedays: 1,
          score: 0.84,
        },
      ],
    },
    mean_reversion_candidates: {
      as_of_date: "2026-07-28",
      formula_version: "rv_mean_reversion_candidates_v1",
      market_state: "WARM",
      input_stock_count: 420,
      candidate_count: 0,
      excluded_stock_count: 8,
      insufficient_history_count: 0,
      items: [],
    },
    factor_screen_candidates: {
      as_of_date: "2026-07-28",
      factor_snapshot_as_of_date: "2026-07-28",
      formula_version: "rv_factor_screen_candidates_v2",
      market_state: "WARM",
      observation_only: true,
      input_stock_count: 1500,
      coverage_count: 1450,
      coverage_denominator: 1500,
      coverage_denominator_as_of_date: "2026-07-28",
      coverage_ratio: 0.9667,
      coverage_threshold: 0.8,
      candidate_count: 1,
      coverage_note: "Factor snapshot landed for 1450 names.",
      items: [
        {
          rank: 1,
          stock_code: "600519.SH",
          stock_name: "Factor Anchor",
          sector_code: "801120",
          sector_name: "Consumer",
          industry: "Beverage",
          score: 0.95,
          pe: 28.4,
          pb: 8.2,
          roe: 0.31,
          gross_margin: 0.56,
          three_month_return: 0.13,
          twelve_month_return: 0.21,
          dividend_yield: 0.02,
        },
      ],
    },
    theme_breakout: {
      as_of_date: "2026-07-28",
      formula_version: "rv_livermore_theme_breakout_proxy_v1",
      is_proxy: true,
      theme_count: 1,
      evidence_state: {
        summary: "Concept membership is proxy-only.",
        inputs: [
          {
            input_family: "concept_membership",
            status: "matched_rows",
            table: "choice_theme_overlay",
            matched_row_count: 24,
            message: "Overlay rows matched.",
          },
        ],
      },
      items: [
        {
          rank: 1,
          as_of_date: "2026-07-28",
          theme_key: "ai-compute",
          theme_name: "AI Compute",
          source_kind: "proxy",
          parent_sector_code: "801001",
          parent_sector_name: "AI",
          parent_sector_rank: 1,
          member_count: 8,
          advance_count: 6,
          advance_ratio: 0.75,
          strong_stock_count: 4,
          limit_stock_count: 1,
          avg_pctchange: 5.1,
          avg_turn: 3.9,
          avg_amplitude: 4.8,
          movement_event_count: 2,
          latest_event_title: "AI acceleration",
          latest_event_time: "14:45",
          observation_only: true,
          reason: "Theme leadership broadened intraday.",
          items: [
            {
              stock_code: "688001.SH",
              stock_name: "Alpha AI",
              sector_code: "801001",
              sector_name: "AI",
              sector_rank: 1,
              open: 20.1,
              high: 21.7,
              low: 19.9,
              close: 21.45,
              pctchange: 9.8,
              turn: 5.4,
              amplitude: 6.1,
              close_strength: 0.81,
              closed_up_limit: false,
              strong: true,
              concept_source_kind: "proxy",
            },
          ],
        },
      ],
      review_items: [
        {
          as_of_date: "2026-07-28",
          theme_key: "ai-compute",
          theme_name: "AI Compute",
          source_kind: "proxy",
          parent_sector_code: "801001",
          parent_sector_name: "AI",
          parent_sector_rank: 1,
          member_count: 8,
          advance_count: 6,
          advance_ratio: 0.75,
          strong_stock_count: 4,
          limit_stock_count: 1,
          avg_pctchange: 5.1,
          avg_turn: 3.9,
          avg_amplitude: 4.8,
          movement_event_count: 2,
          latest_event_title: "AI acceleration",
          latest_event_time: "14:45",
          observation_only: true,
          reason: "Review after close for concept confirmation.",
          items: [
            {
              stock_code: "688001.SH",
              stock_name: "Alpha AI",
              sector_code: "801001",
              sector_name: "AI",
              sector_rank: 1,
              open: 20.1,
              high: 21.7,
              low: 19.9,
              close: 21.45,
              pctchange: 9.8,
              turn: 5.4,
              amplitude: 6.1,
              close_strength: 0.81,
              closed_up_limit: false,
              strong: true,
              concept_source_kind: "proxy",
            },
          ],
          failed_gates: ["concept confirmation pending"],
          failed_gate_codes: ["theme_proxy_only"],
        },
      ],
    },
    hybrid_fusion_candidates: {
      as_of_date: "2026-07-28",
      formula_version: "rv_hybrid_fusion_candidates_v4",
      market_state: "WARM",
      observation_only: true,
      macro_score: 0.73,
      candidate_count: 1,
      coverage_note: "Hybrid fusion uses landed factor and theme evidence.",
      items: [
        {
          rank: 1,
          stock_code: "688001.SH",
          stock_name: "Alpha AI",
          sector_code: "801001",
          sector_name: "AI",
          fusion_score: 0.93,
          cycle_score: 0.74,
          lifecourt_proxy_score: 0.88,
          attention_score: 0.71,
          price_confirm_score: 0.82,
          crowding_penalty: 0.12,
          confidence: "high",
          reason: "Fusion observation-only candidate with aligned cycle and theme evidence.",
          evidence: {
            source_kinds: ["factor_screen", "theme_breakout"],
            macro_ready: true,
          },
          fusion_action: "review",
          factor_rank_available: true,
        },
      ],
    },
    risk_exit: {
      as_of_date: "2026-07-28",
      formula_version: "rv_livermore_risk_exit_ema10_mvp_v1",
      position_count: 2,
      signal_count: 1,
      excluded_position_count: 0,
      insufficient_history_count: 0,
      items: [
        {
          stock_code: "688001.SH",
          stock_name: "Alpha AI",
          reason: "2d_below_ema10",
          entry_cost: 19.8,
          entry_cost_available: true,
          bars_since_entry: 12,
          latest_close: 21.45,
          latest_ema10: 21.8,
          prior_close: 22.1,
          prior_ema10: 21.9,
        },
      ],
      watch_items: [
        {
          stock_code: "300750.SZ",
          stock_name: "Momentum Core",
          entry_cost: 39.6,
          entry_cost_available: true,
          bars_since_entry: 8,
          latest_close: 42.8,
          latest_ema10: 41.7,
          prior_close: 42.1,
          prior_ema10: 41.2,
          exit_watch_price: 41.5,
          triggered: false,
        },
      ],
    },
    workbench_summary: {
      answer_state: "review_ready",
      top_focus: {
        stock_code: "688001.SH",
        stock_name: "Alpha AI",
      },
      follow_ups: [
        "Confirm concept membership after close.",
        "Review exit trigger before next open.",
      ],
    },
  };
}

describe("MarketDataLivermoreBusinessDetail", () => {
  it("renders returned Livermore business modules and nested rows", () => {
    render(<MarketDataLivermoreBusinessDetail payload={buildPayload()} />);

    expect(screen.getByTestId("market-data-detail-livermore-business")).toBeInTheDocument();
    expect(within(screen.getByTestId("market-data-detail-livermore-uptrend-momentum-candidates-table")).getByText("Momentum Core")).toBeInTheDocument();
    expect(within(screen.getByTestId("market-data-detail-livermore-fresh-trend-watchlist-table")).getByText("Fresh Trend")).toBeInTheDocument();
    expect(within(screen.getByTestId("market-data-detail-livermore-hybrid-fusion-candidates-table")).getByText("Fusion observation-only candidate with aligned cycle and theme evidence.")).toBeInTheDocument();
    expect(within(screen.getByTestId("market-data-detail-livermore-risk-exit-items-table")).getByText("2d_below_ema10")).toBeInTheDocument();
    expect(within(screen.getByTestId("market-data-detail-livermore-risk-exit-watch-items-table")).getByText("Momentum Core")).toBeInTheDocument();
    expect(within(screen.getByTestId("market-data-detail-livermore-unsupported-outputs-table")).getByText("mean_reversion_candidates")).toBeInTheDocument();
    expect(within(screen.getByTestId("market-data-detail-livermore-theme-breakout-review-items-table")).getByText("concept confirmation pending, theme_proxy_only")).toBeInTheDocument();
    expect(within(screen.getByTestId("market-data-detail-livermore-cycle-rotation-framework-fusion-policy-matrix-table")).getByText("review")).toBeInTheDocument();
    expect(screen.getByTestId("market-data-detail-livermore-workbench-summary-body")).toHaveTextContent("Confirm concept membership after close.");
  });

  it("distinguishes absent payloads from returned empty module arrays", () => {
    const payload = buildPayload();
    payload.factor_screen_candidates = {
      ...payload.factor_screen_candidates!,
      candidate_count: 0,
      items: [],
    };
    payload.theme_breakout = undefined;

    render(<MarketDataLivermoreBusinessDetail payload={payload} />);

    expect(screen.getByTestId("market-data-detail-livermore-factor-screen-candidates-state")).toHaveTextContent(
      "factor_screen_candidates 已返回，但候选行数量为 0。",
    );
    expect(screen.getByTestId("market-data-detail-livermore-theme-breakout-state")).toHaveTextContent(
      "当前 payload 未返回 theme_breakout。",
    );
  });
});
