import type { CSSProperties } from "react";

import { ibTokens } from "../../../theme/designSystem";

/**
 * Page-scoped CSS variables — aligned with IB light institutional shell.
 */
export const stockAnalysisPageCssVars: CSSProperties = {
  "--sa-dh-page-bg": ibTokens.color.paper,
  "--sa-dh-card": ibTokens.color.surface,
  "--sa-dh-card-soft": ibTokens.color.surfaceMuted,
  "--sa-dh-line": ibTokens.color.hairline,
  "--sa-dh-line-soft": ibTokens.color.hairline,
  "--sa-dh-ink": ibTokens.color.ink,
  "--sa-dh-ink-2": ibTokens.color.inkSecondary,
  "--sa-dh-muted": ibTokens.color.inkSecondary,
  "--sa-dh-muted-2": ibTokens.color.inkMuted,
  "--sa-dh-blue": ibTokens.color.accent,
  "--sa-dh-blue-deep": ibTokens.color.accent,
  "--sa-dh-blue-soft": ibTokens.color.accentSurface,
  "--sa-dh-green": ibTokens.color.up,
  "--sa-dh-green-soft": ibTokens.color.paper,
  "--sa-dh-red": ibTokens.color.down,
  "--sa-dh-shadow-card": "none",
  "--sa-space-2": "8px",
  "--sa-space-3": "12px",
  "--sa-space-4": "16px",
  "--sa-radius-md": "var(--ib-radius, 2px)",
  "--sa-color-surface": ibTokens.color.paper,
  "--sa-color-card": ibTokens.color.surface,
  "--sa-color-border": ibTokens.color.hairline,
  "--sa-color-border-subtle": ibTokens.color.hairline,
  "--sa-color-text": ibTokens.color.ink,
  "--sa-color-muted": ibTokens.color.inkSecondary,
  "--sa-color-eyebrow": ibTokens.color.inkMuted,
  "--sa-table-header-bg": ibTokens.color.surface,
  "--sa-accent-bg-soft": ibTokens.color.paper,
  "--sa-accent-border": ibTokens.color.hairline,
  "--sa-accent-text": ibTokens.color.accent,
  "--sa-accent-line": ibTokens.color.accent,
  "--sa-sem-up-soft": ibTokens.color.paper,
  "--sa-sem-up-border": ibTokens.color.hairline,
  "--sa-sem-up-text": ibTokens.color.up,
  "--sa-sem-down-soft": ibTokens.color.paper,
  "--sa-sem-down-border": ibTokens.color.hairline,
  "--sa-sem-down-text": ibTokens.color.down,
  "--sa-sem-loss": ibTokens.color.down,
  "--sa-sem-profit": ibTokens.color.up,
  "--sa-warning-fg": ibTokens.color.warn,
  "--sa-warning-soft-bg": ibTokens.color.paper,
  "--sa-warning-border": ibTokens.color.hairline,
  "--sa-danger-soft-bg": ibTokens.color.paper,
  "--sa-danger-border": ibTokens.color.hairline,
  "--sa-danger-text": ibTokens.color.down,
  "--sa-chart-track": ibTokens.color.hairline,
  "--sa-font-tabular": "var(--moss-font-mono), ui-monospace, monospace",
} as CSSProperties;
