import type { CSSProperties } from "react";

/**
 * Page-scoped CSS variables — aliased onto the official --dh-api-* dark
 * palette (DESIGN.md §2.2). The var() references require a `theme-dh-api`
 * class on the same element or an ancestor (page root and drawer bodies
 * carry it), because drawers render in portals outside the page root.
 */
export const stockAnalysisPageCssVars: CSSProperties = {
  "--sa-dh-page-bg": "var(--dh-api-bg)",
  "--sa-dh-card": "var(--dh-api-panel)",
  "--sa-dh-card-soft": "var(--dh-api-panel-2)",
  "--sa-dh-line": "var(--dh-api-line-soft)",
  "--sa-dh-line-soft": "var(--dh-api-line-soft)",
  "--sa-dh-ink": "var(--dh-api-ink)",
  "--sa-dh-ink-2": "var(--dh-api-soft)",
  "--sa-dh-muted": "var(--dh-api-muted)",
  "--sa-dh-muted-2": "var(--dh-api-muted)",
  "--sa-dh-blue": "var(--dh-api-blue)",
  "--sa-dh-blue-deep": "var(--dh-api-blue)",
  "--sa-dh-blue-soft": "var(--dh-api-blue-soft)",
  "--sa-dh-green": "var(--dh-api-green)",
  "--sa-dh-green-soft": "var(--dh-api-green-soft)",
  "--sa-dh-red": "var(--dh-api-red)",
  "--sa-dh-shadow-card": "none",
  "--sa-space-2": "8px",
  "--sa-space-3": "12px",
  "--sa-space-4": "16px",
  "--sa-radius-md": "var(--dh-api-radius, 6px)",
  "--sa-color-surface": "var(--dh-api-bg)",
  "--sa-color-card": "var(--dh-api-panel)",
  "--sa-color-border": "var(--dh-api-line)",
  "--sa-color-border-subtle": "var(--dh-api-line-soft)",
  "--sa-color-text": "var(--dh-api-ink)",
  "--sa-color-muted": "var(--dh-api-soft)",
  "--sa-color-eyebrow": "var(--dh-api-muted)",
  "--sa-table-header-bg": "var(--dh-api-panel)",
  "--sa-accent-bg-soft": "var(--dh-api-blue-soft)",
  "--sa-accent-border": "var(--dh-api-blue)",
  "--sa-accent-text": "var(--dh-api-blue)",
  "--sa-accent-line": "var(--dh-api-blue)",
  "--sa-sem-up-soft": "var(--dh-api-green-soft)",
  "--sa-sem-up-border": "var(--dh-api-green-soft)",
  "--sa-sem-up-text": "var(--dh-api-green)",
  "--sa-sem-down-soft": "var(--dh-api-red-soft)",
  "--sa-sem-down-border": "var(--dh-api-red-soft)",
  "--sa-sem-down-text": "var(--dh-api-red)",
  "--sa-sem-loss": "var(--dh-api-red)",
  "--sa-sem-profit": "var(--dh-api-green)",
  "--sa-warning-fg": "var(--dh-api-amber)",
  "--sa-warning-soft-bg": "var(--dh-api-amber-soft)",
  "--sa-warning-border": "var(--dh-api-line)",
  "--sa-danger-soft-bg": "var(--dh-api-red-soft)",
  "--sa-danger-border": "var(--dh-api-red-soft)",
  "--sa-danger-text": "var(--dh-api-red)",
  "--sa-chart-track": "var(--dh-api-line-soft)",
  "--sa-font-tabular": "var(--moss-font-mono), ui-monospace, monospace",

  "--ib-paper": "var(--dh-api-bg)",
  "--ib-surface": "var(--dh-api-panel)",
  "--ib-surface-muted": "var(--dh-api-panel-2)",
  "--ib-hairline": "var(--dh-api-line)",
  "--ib-rule-strong": "rgba(255, 255, 255, 0.18)",
  "--ib-ink": "var(--dh-api-ink)",
  "--ib-ink-secondary": "var(--dh-api-soft)",
  "--ib-ink-muted": "var(--dh-api-muted)",
  "--ib-accent": "var(--dh-api-blue)",
  "--ib-accent-hover": "#93bfff",
  "--ib-accent-surface": "var(--dh-api-blue-soft)",
  "--ib-up": "var(--dh-api-green)",
  "--ib-down": "var(--dh-api-red)",
  "--ib-warn": "var(--dh-api-amber)",
  "--ib-gold": "var(--dh-api-amber)",
} as CSSProperties;
