"""Path-triggered PR regressions for caliber, formal compute and balance updates.

The six caliber red-line tests (tests/test_caliber_rule_*.py) are also
unconditional members of the bounded release suite
(scripts/backend_release_suite.py, since 2026-08-12). This gate is the
targeted fast-reaction half of that double insurance: when the PR diff
touches a mapped source module, the matching test files run directly, so a
regression is attributed to the diff that caused it instead of surfacing as
a generic suite failure.

``CALIBER_GATE_MAP`` retains the six caliber rules and adds existing independent
goldens for curves, duration, KRD, PnL bridge and FX, plus balance and PnL
materialization checks. Entries follow verified test imports and their direct
production dependencies; this is not a claim of all core_finance coverage.
Only the curve-engine package has a prefix entry, so newly added implementations
there select its existing goldens without matching unrelated finance modules.
Mapped test changes run that test and the mapping guard. Gate changes run all
registered checks. No expected financial values are generated by this script.
First-scope data-update and balance-read paths also select their focused checks;
frontend changes select a separate bounded Vitest job.

Usage::

    python scripts/check_caliber_gate.py --base-ref origin/main [--dry-run]

Fail-closed: if the diff against ``--base-ref`` cannot be computed (unknown
ref, git unavailable, not a repository), the gate exits non-zero instead of
silently passing.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

_TEST_ACCOUNTING_BASIS = "tests/test_caliber_rule_accounting_basis.py"
_TEST_FORMAL_SCENARIO_GATE = "tests/test_caliber_rule_formal_scenario_gate.py"
_TEST_FX_MID_CONVERSION = "tests/test_caliber_rule_fx_mid_conversion.py"
_TEST_HAT_MAPPING = "tests/test_caliber_rule_hat_mapping.py"
_TEST_ISSUANCE_EXCLUSION = "tests/test_caliber_rule_issuance_exclusion.py"
_TEST_SUBJECT_MERGE = "tests/test_caliber_rule_subject_514_516_517_merge.py"
_TEST_CURVE = "tests/test_curve_engine_golden.py"
_TEST_DURATION = "tests/test_bond_duration_goldens.py"
_TEST_COUPON_DATES = "tests/test_bond_coupon_date_boundary.py"
_TEST_KRD = "tests/test_krd_golden.py"
_TEST_PNL_BRIDGE = "tests/test_pnl_bridge_golden.py"
_TEST_PNL_BRIDGE_DURATION = "tests/test_pnl_bridge_modified_duration.py"
_TEST_CAMPISI = "tests/test_campisi.py"
_TEST_CAMPISI_GOLDEN = "tests/test_campisi_formula_golden.py"
_TEST_CAMPISI_DECIMAL_LOCK = "tests/test_decimal_first_batch_lock.py"
_TEST_CAMPISI_SERVICE = "tests/test_campisi_attribution_service.py"
_TEST_PNL_AUDIT = "tests/test_pnl_audit_regressions.py"
_TEST_ATTRIBUTION_WORKBENCH = "tests/test_pnl_attribution_workbench_contract.py"
_TEST_ATTRIBUTION_SERVICE = "tests/test_pnl_attribution_service_explicit_numeric.py"
_TEST_FX = "tests/test_fx_rates_golden.py"
_TEST_FORMAL_FX_VALIDITY = "tests/test_formal_fx_rate_validity.py"
_TEST_FX_MATERIALIZE = "tests/test_fx_mid_materialize.py"
_TEST_BALANCE_CORE = "tests/test_balance_analysis_core.py"
_TEST_BALANCE_FLOW = "tests/test_balance_analysis_materialize_flow.py"
_TEST_BALANCE_CONSISTENCY = "tests/test_balance_analysis_snapshot_fact_consistency.py"
_TEST_PNL_FLOW = "tests/test_pnl_materialize_flow.py"
_TEST_PRODUCT_REFERENCE = "tests/test_product_category_manual_reference_flow.py"
_TEST_PRODUCT_INCREMENTAL = "tests/test_product_category_incremental_materialization.py"
_TEST_PRODUCT_API_CONTRACT = "tests/test_product_category_api_contract.py"
_TEST_PNL_INVALIDATION = "tests/test_pnl_fact_precompute_invalidation.py"
_TEST_PNL_PRECOMPUTE_STATE = "tests/test_pnl_by_business_precompute_state.py"
_TEST_PNL_INDEPENDENT_RECONCILIATION = "tests/test_pnl_independent_reconciliation.py"
_TEST_PNL_INDEPENDENT_REFERENCE_API = (
    "tests/test_pnl_overview_independent_reference_api.py"
)
_TEST_FINANCIAL_PUBLICATION = "tests/test_financial_result_publication.py"
_TEST_PNL_PAGE_LIFECYCLE = "tests/test_pnl_by_business_page_lifecycle.py"
_TEST_PNL_PUBLICATION_API = "tests/test_pnl_publication_api_contract.py"
_TEST_PNL_ADJUSTMENT_HANDOFF = "tests/test_pnl_by_business_adjustment_handoff.py"
_TEST_PNL_CANDIDATE_INSIGHTS = (
    "tests/test_pnl_by_business_candidate_insights_contract.py"
)
_TEST_PNL_INSIGHTS = "tests/test_pnl_by_business_insights_contract.py"
_TEST_GLOBAL_REFRESH = "tests/test_global_data_refresh.py"
_TEST_DATA_UPDATES = "tests/test_data_updates.py"
_TEST_SYSTEM_PUBLICATION = "tests/test_system_read_publication.py"
_TEST_WORKER_BOOTSTRAP = "tests/test_worker_bootstrap.py"
_TEST_FORMAL_JOINT_REPLAY = "tests/test_formal_compute_joint_replay.py"
_TEST_BALANCE_PUBLICATION = "tests/test_balance_analysis_overview_publication.py"
_TEST_MAPPING = "tests/test_caliber_gate_mapping.py"
_TEST_DATA_UPDATE_BALANCE_INTEGRATION = "tests/test_data_update_balance_integration.py"
_TEST_QUEUE_LAUNCHER = "tests/test_data_update_queue_launcher_logging.py"
_TEST_QUEUE_INSTALLER = "tests/test_install_data_update_queue.py"
_TEST_DATA_HEALTH = "tests/test_data_health.py"
_TEST_DATA_HEALTH_SCHTASKS_QUERY = "tests/test_data_health_schtasks_query.py"
_TEST_BALANCE_API = "tests/test_balance_analysis_api.py"

_ALL_CALIBER_TESTS = (
    _TEST_ACCOUNTING_BASIS,
    _TEST_FORMAL_SCENARIO_GATE,
    _TEST_FX_MID_CONVERSION,
    _TEST_HAT_MAPPING,
    _TEST_ISSUANCE_EXCLUSION,
    _TEST_SUBJECT_MERGE,
)

# Source file -> existing financial checks that must run when the file changes.
# Keys are repo-relative POSIX paths; a key ending with "/" is a prefix match.
CALIBER_GATE_MAP: dict[str, tuple[str, ...]] = {
    # Shared caliber framework: every caliber test starts with
    # `from backend.app.core_finance.calibers import ...`. The package
    # __init__ re-exports enums/descriptor/registry symbols used by the
    # tests (Basis/View/Resolution/ALL_CELLS, get_caliber_rule,
    # assert_canonical_callsite, CaliberCalibrationViolation), and
    # rules/__init__ side-effect-registers every bundled rule descriptor
    # (asserted by each test's *_is_registered_after_package_import case).
    "backend/app/core_finance/calibers/__init__.py": _ALL_CALIBER_TESTS,
    "backend/app/core_finance/calibers/descriptor.py": _ALL_CALIBER_TESTS,
    "backend/app/core_finance/calibers/enums.py": _ALL_CALIBER_TESTS,
    "backend/app/core_finance/calibers/registry.py": _ALL_CALIBER_TESTS,
    "backend/app/core_finance/calibers/rules/__init__.py": _ALL_CALIBER_TESTS,
    # Rule modules: each caliber test imports its own DESCRIPTOR module.
    "backend/app/core_finance/calibers/rules/accounting_basis.py": (
        _TEST_ACCOUNTING_BASIS,
    ),
    "backend/app/core_finance/calibers/rules/formal_scenario_gate.py": (
        _TEST_FORMAL_SCENARIO_GATE,
    ),
    "backend/app/core_finance/calibers/rules/fx_mid_conversion.py": (
        _TEST_FX_MID_CONVERSION,
    ),
    "backend/app/core_finance/calibers/rules/hat_mapping.py": (
        _TEST_HAT_MAPPING,
    ),
    "backend/app/core_finance/calibers/rules/issuance_exclusion.py": (
        _TEST_ISSUANCE_EXCLUSION,
    ),
    "backend/app/core_finance/calibers/rules/subject_514_516_517_merge.py": (
        _TEST_SUBJECT_MERGE,
    ),
    # Canonical modules imported by specific tests, either statically
    # (subject merge: LEDGER_PNL_ACCOUNT_PREFIXES; accounting basis:
    # derive_accounting_basis_value) or via
    # importlib.import_module(DESCRIPTOR.canonical_module) (hat mapping,
    # issuance exclusion, fx mid conversion).
    "backend/app/core_finance/config/classification_rules.py": (
        _TEST_HAT_MAPPING,
        _TEST_ISSUANCE_EXCLUSION,
        _TEST_SUBJECT_MERGE,
        _TEST_BALANCE_CORE,
        _TEST_DURATION,
        _TEST_KRD,
        _TEST_PNL_FLOW,
        _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/core_finance/field_normalization.py": (
        _TEST_ACCOUNTING_BASIS,
        _TEST_BALANCE_CORE,
        _TEST_DURATION,
        _TEST_KRD,
        _TEST_PNL_FLOW,
        _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/core_finance/fx_rates.py": (
        _TEST_FX_MID_CONVERSION,
        _TEST_FX,
        "tests/test_fx_rates.py",
        _TEST_FORMAL_FX_VALIDITY,
        _TEST_FX_MATERIALIZE,
        _TEST_BALANCE_FLOW,
        _TEST_PNL_FLOW,
    ),
    # Curve tests import bootstrapper/types/interpolation/NS directly; PnL
    # bridge consumes curve_types and interpolation from the same package.
    "backend/app/core_finance/curve_engine/": (_TEST_CURVE, _TEST_PNL_BRIDGE),
    "backend/app/core_finance/pnl_bridge.py": (
        _TEST_PNL_BRIDGE, _TEST_PNL_BRIDGE_DURATION,
        "tests/test_pnl_bridge_core.py", "tests/test_pnl_bridge_ambiguity.py",
        "tests/test_pnl_api_contract.py",
        "tests/test_campisi_dirty_input.py",
    ),
    "backend/app/services/pnl_bridge_service.py": (
        _TEST_PNL_BRIDGE, "tests/test_pnl_bridge_core.py",
        "tests/test_pnl_bridge_ambiguity.py",
        "tests/test_pnl_api_contract.py", "tests/test_campisi_dirty_input.py",
    ),
    # These numerical paths were absent from the path-trigger gate. Keep the
    # independent formulas, null semantics and service boundary checks together.
    "backend/app/core_finance/campisi.py": (
        _TEST_CAMPISI, _TEST_CAMPISI_GOLDEN, _TEST_CAMPISI_DECIMAL_LOCK, _TEST_PNL_AUDIT,
        "tests/test_attribution_daily.py",
    ),
    "backend/app/services/campisi_attribution_service.py": (
        _TEST_CAMPISI_SERVICE, _TEST_PNL_AUDIT,
        "tests/test_campisi_dirty_input.py",
    ),
    "backend/app/core_finance/pnl_attribution/workbench.py": (
        _TEST_ATTRIBUTION_WORKBENCH, _TEST_PNL_AUDIT,
    ),
    "backend/app/services/pnl_attribution_service.py": (
        _TEST_ATTRIBUTION_SERVICE, _TEST_PNL_AUDIT,
    ),
    "backend/app/core_finance/attribution_daily.py": (
        "tests/test_attribution_daily.py", _TEST_CAMPISI_GOLDEN,
    ),
    "backend/app/core_finance/credit_spread_analysis.py": (
        "backend/tests/core_finance/test_credit_spread_analysis.py",
        "tests/test_credit_spread_analysis.py",
    ),
    "backend/app/core_finance/balance_analysis_workbook.py": (
        "tests/test_balance_workbook_decimal_nan_guard.py",
    ),
    "backend/app/core_finance/balance_workbook/_utils.py": (
        "tests/test_balance_workbook_decimal_nan_guard.py",
    ),
    # Duration delegates discounting to common; KRD imports bond_duration.
    # These are numerical checks of those paths, not the whole risk tensor.
    "backend/app/core_finance/bond_duration.py": (
        _TEST_DURATION, _TEST_KRD, _TEST_COUPON_DATES, _TEST_CAMPISI_DECIMAL_LOCK,
        "tests/test_bond_duration.py",
    ),
    "backend/app/core_finance/bond_analytics/common.py": (
        "tests/test_bond_analytics_core.py",
        "tests/test_bond_analytics_engine.py",
        "tests/test_bond_duration.py",
        "tests/test_bond_four_effects.py",
        _TEST_DURATION,
        _TEST_KRD,
        _TEST_PNL_BRIDGE,
        _TEST_PNL_BRIDGE_DURATION,
        _TEST_COUPON_DATES,
        _TEST_CAMPISI_DECIMAL_LOCK,
    ),
    "backend/app/core_finance/krd.py": (_TEST_KRD, _TEST_COUPON_DATES, "tests/test_krd.py"),
    "backend/app/core_finance/credit_spread.py": ("tests/test_credit_spread.py",),
    # The date boundary test independently enumerates coupon months forward
    # and checks common, engine, KRD and Campisi entrypoints. Production common
    # obtains its backwards coupon schedule from cashflow_projection.
    "backend/app/core_finance/bond_analytics/engine.py": (
        _TEST_COUPON_DATES, "tests/test_bond_analytics_core.py",
        "tests/test_bond_analytics_engine.py",
    ),
    "backend/app/core_finance/bond_four_effects.py": (
        _TEST_COUPON_DATES, _TEST_CAMPISI_GOLDEN, _TEST_CAMPISI_DECIMAL_LOCK, _TEST_PNL_AUDIT,
        "tests/test_bond_four_effects.py",
    ),
    "backend/app/core_finance/cashflow_projection.py": (
        _TEST_COUPON_DATES, _TEST_CAMPISI_DECIMAL_LOCK,
    ),
    "backend/app/core_finance/risk_tensor.py": (_TEST_KRD,),
    "backend/app/core_finance/attribution_core.py": (_TEST_KRD,),
    "backend/app/core_finance/accounting_basis_constants.py": (
        _TEST_PNL_BRIDGE,
        _TEST_BALANCE_CORE,
        _TEST_PNL_FLOW,
    ),
    # Shared conversions must exercise consumers as well as helper contracts:
    # rate_units -> bridge/KRD; safe_decimal -> common/KRD;
    # decimal_utils -> FX and formal PnL normalization.
    "backend/app/core_finance/rate_units.py": (
        "tests/test_rate_units.py",
        "tests/test_rate_units_decimal.py",
        _TEST_CAMPISI,
        _TEST_PNL_AUDIT,
        _TEST_PNL_BRIDGE,
        _TEST_KRD,
    ),
    "backend/app/core_finance/safe_decimal.py": (
        _TEST_DURATION,
        _TEST_KRD,
        _TEST_PNL_BRIDGE,
    ),
    "backend/app/core_finance/decimal_utils.py": (
        "tests/test_decimal_utils_strict.py",
        _TEST_FX,
        _TEST_PNL_FLOW,
    ),
    # Both formal balance and PnL use the FX calendar for admissible dates.
    "backend/app/core_finance/fx_calendar.py": (
        _TEST_FX,
        "tests/test_fx_calendar.py",
        "tests/test_fx_rates.py",
        _TEST_FORMAL_FX_VALIDITY,
        _TEST_FX_MATERIALIZE,
        _TEST_BALANCE_FLOW,
        _TEST_PNL_FLOW,
    ),
    "backend/app/tasks/fx_mid_materialize.py": (
        _TEST_BALANCE_FLOW, _TEST_FX_MATERIALIZE, _TEST_FORMAL_FX_VALIDITY,
    ),
    "backend/app/repositories/adb_analysis_repo.py": (
        "tests/test_adb_snapshot_fx_fallback.py", _TEST_FORMAL_FX_VALIDITY,
    ),
    "backend/app/core_finance/balance_analysis.py": (
        _TEST_BALANCE_CORE,
        _TEST_BALANCE_FLOW,
        _TEST_BALANCE_CONSISTENCY,
        _TEST_BALANCE_API,
    ),
    "backend/app/repositories/balance_analysis_repo.py": (
        _TEST_FORMAL_FX_VALIDITY,
        _TEST_BALANCE_FLOW,
        _TEST_BALANCE_CONSISTENCY,
        _TEST_PNL_INVALIDATION,
        _TEST_BALANCE_PUBLICATION,
        _TEST_BALANCE_API,
    ),
    "backend/app/tasks/balance_analysis_materialize.py": (
        _TEST_BALANCE_FLOW,
        _TEST_BALANCE_CONSISTENCY,
        _TEST_BALANCE_PUBLICATION,
        _TEST_FORMAL_JOINT_REPLAY,
        _TEST_BALANCE_API,
    ),
    "backend/app/repositories/snapshot_repo.py": (
        _TEST_BALANCE_FLOW,
        _TEST_BALANCE_CONSISTENCY,
        "tests/test_snapshot_dq_guardrails.py",
        "tests/test_snapshot_materialize_flow.py",
    ),
    "backend/app/tasks/snapshot_materialize.py": (
        "tests/test_snapshot_dq_guardrails.py",
        "tests/test_snapshot_materialize_flow.py",
    ),
    "backend/app/core_finance/pnl.py": (_TEST_PNL_FLOW,),
    "backend/app/core_finance/pnl_constants.py": (_TEST_PNL_FLOW,),
    "backend/app/tasks/pnl_materialize.py": (
        _TEST_FORMAL_FX_VALIDITY,
        _TEST_PNL_FLOW,
        _TEST_PNL_INVALIDATION,
        _TEST_FORMAL_JOINT_REPLAY,
    ),
    "backend/app/tasks/bond_analytics_materialize.py": (
        _TEST_FORMAL_JOINT_REPLAY,
    ),
    "backend/app/tasks/risk_tensor_materialize.py": (
        _TEST_FORMAL_JOINT_REPLAY,
    ),
    # PnL fact revisions invalidate derived page state. These checks exercise
    # commit/rollback semantics and the pinned dependency revision used by the
    # precompute worker, rather than treating an old page row as current.
    "backend/app/repositories/pnl_precompute_state.py": (
        _TEST_PNL_INVALIDATION,
        _TEST_PNL_PRECOMPUTE_STATE,
    ),
    "backend/app/repositories/pnl_repo.py": (
        _TEST_FORMAL_FX_VALIDITY,
        _TEST_PNL_INVALIDATION,
        _TEST_PNL_PRECOMPUTE_STATE,
        _TEST_PNL_INDEPENDENT_RECONCILIATION,
    ),
    "backend/app/tasks/pnl_by_business_precompute.py": (
        _TEST_PNL_INVALIDATION,
        _TEST_PNL_PRECOMPUTE_STATE,
    ),
    "backend/app/services/pnl_service_by_business_support.py": (
        _TEST_PNL_PRECOMPUTE_STATE,
        _TEST_PNL_PAGE_LIFECYCLE,
    ),
    "backend/app/services/pnl_by_business_precompute_lifecycle.py": (
        _TEST_PNL_PRECOMPUTE_STATE,
        _TEST_PNL_ADJUSTMENT_HANDOFF,
        _TEST_PNL_PAGE_LIFECYCLE,
    ),
    "backend/app/services/pnl_task_dispatch.py": (
        _TEST_PNL_PAGE_LIFECYCLE,
        _TEST_PNL_PUBLICATION_API,
    ),
    "backend/app/services/pnl_by_business_adjustment_handoff.py": (
        _TEST_PNL_ADJUSTMENT_HANDOFF,
        _TEST_PNL_PAGE_LIFECYCLE,
    ),
    # Financial publication has one immutable writer/reader protocol. The page
    # lifecycle and HTTP contract checks stay attached only to their adapters.
    "backend/app/repositories/financial_result_publication_repo.py": (
        _TEST_FINANCIAL_PUBLICATION,
        _TEST_BALANCE_PUBLICATION,
        _TEST_SYSTEM_PUBLICATION,
    ),
    "backend/app/tasks/financial_result_publication.py": (
        _TEST_FINANCIAL_PUBLICATION,
        _TEST_BALANCE_PUBLICATION,
        _TEST_SYSTEM_PUBLICATION,
    ),
    "backend/app/tasks/balance_analysis_overview_publication.py": (
        _TEST_BALANCE_PUBLICATION,
    ),
    "backend/app/services/balance_analysis_publication_service.py": (
        _TEST_BALANCE_PUBLICATION,
    ),
    "backend/app/services/balance_analysis_service.py": (
        _TEST_BALANCE_PUBLICATION,
        _TEST_BALANCE_API,
    ),
    "backend/app/api/routes/balance_analysis.py": (
        _TEST_BALANCE_PUBLICATION,
        _TEST_BALANCE_API,
    ),
    "backend/app/schemas/balance_analysis.py": (
        _TEST_BALANCE_PUBLICATION,
        _TEST_BALANCE_API,
    ),
    "backend/app/governance/settings.py": (
        _TEST_BALANCE_PUBLICATION,
    ),
    "backend/app/tasks/pnl_by_business_page_publication.py": (
        _TEST_FINANCIAL_PUBLICATION,
        _TEST_PNL_PAGE_LIFECYCLE,
    ),
    "backend/app/services/pnl_by_business_page_lifecycle.py": (
        _TEST_PNL_PAGE_LIFECYCLE,
    ),
    "backend/app/services/pnl_by_business_page_readiness.py": (
        _TEST_PNL_PAGE_LIFECYCLE,
    ),
    "backend/app/services/pnl_by_business_publication_service.py": (
        _TEST_PNL_PAGE_LIFECYCLE,
        _TEST_PNL_PUBLICATION_API,
    ),
    "backend/app/services/pnl_by_business_page_dates.py": (
        _TEST_PNL_PUBLICATION_API,
    ),
    "backend/app/core_finance/pnl_by_business_insights.py": (
        _TEST_PNL_CANDIDATE_INSIGHTS,
        _TEST_PNL_INSIGHTS,
    ),
    "backend/app/services/pnl_by_business_candidate_insights.py": (
        _TEST_FINANCIAL_PUBLICATION,
        _TEST_PNL_CANDIDATE_INSIGHTS,
        _TEST_PNL_PAGE_LIFECYCLE,
    ),
    "scripts/run_global_data_refresh.py": (
        _TEST_FINANCIAL_PUBLICATION,
        _TEST_GLOBAL_REFRESH,
        _TEST_DATA_UPDATES,
        _TEST_SYSTEM_PUBLICATION,
    ),
    # Request persistence and the worker share the publication-failure boundary:
    # completed financial work must never be replayed by a publication retry.
    "backend/app/api/routes/data_updates.py": (
        _TEST_DATA_UPDATES, _TEST_DATA_UPDATE_BALANCE_INTEGRATION,
    ),
    "backend/app/services/data_update_service.py": (
        _TEST_DATA_UPDATES, _TEST_DATA_UPDATE_BALANCE_INTEGRATION,
    ),
    "backend/app/repositories/data_update_repo.py": (
        _TEST_DATA_UPDATES, _TEST_SYSTEM_PUBLICATION,
        _TEST_DATA_UPDATE_BALANCE_INTEGRATION,
    ),
    "backend/app/tasks/data_update_center.py": (
        _TEST_DATA_UPDATES, _TEST_SYSTEM_PUBLICATION,
        _TEST_DATA_UPDATE_BALANCE_INTEGRATION,
    ),
    "backend/app/tasks/system_read_publication.py": (_TEST_SYSTEM_PUBLICATION,),
    "backend/app/repositories/system_read_publication_repo.py": (_TEST_SYSTEM_PUBLICATION,),
    "backend/app/tasks/worker_bootstrap.py": (_TEST_WORKER_BOOTSTRAP,),
    "backend/app/tasks/worker_recovery.py": (_TEST_WORKER_BOOTSTRAP,),
    "backend/app/tasks/broker.py": (_TEST_WORKER_BOOTSTRAP,),
    "backend/app/tasks/pnl_by_business_resource_scope.py": (
        _TEST_FINANCIAL_PUBLICATION,
        _TEST_PNL_PRECOMPUTE_STATE,
    ),
    # Independent reconciliation keeps the numerical comparator and the
    # persisted/read API reference path covered separately.
    "backend/app/core_finance/pnl_independent_reconciliation.py": (
        _TEST_PNL_INDEPENDENT_RECONCILIATION,
    ),
    "backend/app/repositories/pnl_independent_reference_repo.py": (
        _TEST_PNL_INDEPENDENT_RECONCILIATION,
        _TEST_PNL_INDEPENDENT_REFERENCE_API,
    ),
    "backend/app/services/pnl_independent_reference_service.py": (
        _TEST_PNL_INDEPENDENT_RECONCILIATION,
        _TEST_PNL_INDEPENDENT_REFERENCE_API,
    ),
    "backend/app/services/pnl_service.py": (
        _TEST_PNL_INDEPENDENT_RECONCILIATION,
        _TEST_PNL_INDEPENDENT_REFERENCE_API,
    ),
    "backend/app/api/routes/pnl.py": (
        _TEST_PNL_INDEPENDENT_REFERENCE_API,
        _TEST_PNL_PUBLICATION_API,
    ),
    # The existing product reference starts at synthetic source workbooks,
    # runs the real materializer, and checks persisted rows plus HTTP output.
    # Annual reuse also fingerprints these production dependencies. A source,
    # schema or implementation change must exercise rebuild-versus-reuse checks.
    "backend/app/core_finance/product_category_pnl.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/config/product_category_mapping.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/core_finance/config/product_category_mapping.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/core_finance/config/product_category_contract.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/services/product_category_source_service.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/services/source_file_hash.py": (_TEST_PRODUCT_INCREMENTAL,),
    "backend/app/tasks/product_category_pnl.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/tasks/product_category_refresh_state.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/repositories/product_category_pnl_repo.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/schema_registry/duckdb/08_product_category_pnl.sql": (
        _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/services/product_category_pnl_service.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_API_CONTRACT,
    ),
    "backend/app/api/routes/product_category_pnl.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_API_CONTRACT,
    ),
    # Refresh inherits CacheBuildRunRecord; the HTTP contract also proves that
    # the OpenAPI checker notices removals from nested product response models.
    "backend/app/schemas/product_category_pnl.py": (_TEST_PRODUCT_API_CONTRACT,),
    "backend/app/schemas/materialize.py": (_TEST_PRODUCT_API_CONTRACT,),
    "scripts/api_contract_check.py": (_TEST_PRODUCT_API_CONTRACT,),
    "backend/app/core_finance/reconciliation_checks.py": (
        "tests/test_reconciliation_checks.py",
    ),
    # First-scope request, receipt, and balance read path on codex/V1.
    "backend/app/api/__init__.py": (_TEST_DATA_UPDATES, _TEST_DATA_UPDATE_BALANCE_INTEGRATION),
    "backend/app/schemas/data_updates.py": (_TEST_DATA_UPDATES, _TEST_DATA_UPDATE_BALANCE_INTEGRATION),
    "backend/app/api/routes/data_health.py": (_TEST_DATA_HEALTH, _TEST_DATA_UPDATES),
    "backend/app/services/data_health_service.py": (
        _TEST_DATA_HEALTH,
        _TEST_DATA_HEALTH_SCHTASKS_QUERY,
        _TEST_DATA_UPDATES,
    ),
    "scripts/scheduling/drain_data_updates.ps1": (_TEST_QUEUE_LAUNCHER, _TEST_QUEUE_INSTALLER),
    "scripts/scheduling/install_data_update_queue.ps1": (_TEST_QUEUE_INSTALLER,),
    _TEST_DATA_UPDATES: (_TEST_DATA_UPDATES,),
    _TEST_DATA_UPDATE_BALANCE_INTEGRATION: (_TEST_DATA_UPDATE_BALANCE_INTEGRATION,),
    _TEST_QUEUE_LAUNCHER: (_TEST_QUEUE_LAUNCHER,),
    _TEST_QUEUE_INSTALLER: (_TEST_QUEUE_INSTALLER,),
    _TEST_DATA_HEALTH_SCHTASKS_QUERY: (_TEST_DATA_HEALTH_SCHTASKS_QUERY,),
    _TEST_BALANCE_API: (_TEST_BALANCE_API,),
}

# Relevant frontend edits need the bounded page/API checks in the V1 PR job.
# Keep these paths exact where possible so unrelated features do not install npm.
FRONTEND_FIRST_SCOPE_PATHS = (
    "frontend/src/features/platform-config/",
    "frontend/src/features/balance-analysis/",
    "frontend/src/api/dataUpdatesClient.ts",
    "frontend/src/api/dataUpdatesClient.test.ts",
    "frontend/src/api/balanceAnalysisClient.ts",
    "frontend/src/api/balanceAnalysisClient.datesContract.test.ts",
    "frontend/src/api/balanceMovementClient.ts",
    "frontend/src/api/balanceMovementClient.test.ts",
    "frontend/src/api/homeSupplementalClient.ts",
    "frontend/src/api/clientContext.ts",
    "frontend/src/api/transport.ts",
    "frontend/src/api/contracts/balanceLedger.ts",
    "frontend/src/test/PlatformConfigPage.test.tsx",
    "frontend/src/test/BalanceAnalysisDateSemanticsContract.test.tsx",
    "frontend/src/test/BalanceAnalysisPage.test.tsx",
    "frontend/src/test/BalanceMovementRequestBoundary.test.tsx",
    "frontend/tests/playwright/data-update-center-balance-daily.spec.mjs",
)

DATA_UPDATE_BROWSER_PATHS = (
    "frontend/src/features/platform-config/",
    "frontend/src/api/dataUpdatesClient.ts",
    "frontend/src/api/dataUpdatesClient.test.ts",
    "frontend/src/api/balanceAnalysisClient.ts",
    "frontend/src/api/homeSupplementalClient.ts",
    "frontend/tests/playwright/data-update-center-balance-daily.spec.mjs",
)

SCHEDULER_WINDOWS_PATHS = (
    "scripts/scheduling/drain_data_updates.ps1",
    "scripts/scheduling/install_data_update_queue.ps1",
    _TEST_QUEUE_LAUNCHER,
    _TEST_QUEUE_INSTALLER,
)

# Formal calculation and release-cutoff edits still require the canonical
# bounded release suite; ordinary data-update orchestration does not.
FORMAL_RELEASE_PATHS = (
    "backend/app/core_finance/",
    "backend/app/tasks/formal_balance_pipeline.py",
    "backend/app/tasks/balance_analysis_materialize.py",
    "scripts/backend_release_suite.py",
    "docs/V3_CUTOFF_EXIT_CRITERIA.md",
)

# Read and publication boundaries share production dependencies with the
# numerical checks above. Extend those exact paths without widening prefixes.
for _source in (
    "backend/app/main.py",
    "backend/app/repositories/duckdb_read_context.py",
    "backend/app/repositories/duckdb_repo.py",
    "backend/app/repositories/cube_query_repo.py",
    "backend/app/repositories/governance_repo.py",
    "backend/app/observability/response_cache.py",
    "backend/app/services/runtime_cache.py",
    "backend/app/services/executive_service.py",
    "backend/app/services/market_home_warmup_service.py",
    "backend/app/services/market_overview_service.py",
    "backend/app/services/pnl_service.py",
    "backend/app/api/routes/system_read_publication.py",
    "backend/app/repositories/system_read_publication_repo.py",
    "backend/app/tasks/system_read_publication.py",
    "backend/app/repositories/financial_result_publication_repo.py",
    "backend/app/tasks/financial_result_publication.py",
):
    CALIBER_GATE_MAP[_source] = (*CALIBER_GATE_MAP.get(_source, ()),
        "tests/test_system_online_read_boundary.py",
        "tests/test_system_online_publication_concurrency.py")
for _source in (
    "backend/app/repositories/system_read_publication_repo.py",
    "backend/app/tasks/system_read_publication.py",
    "backend/app/repositories/financial_result_publication_repo.py",
    "backend/app/tasks/financial_result_publication.py",
    "backend/app/repositories/data_update_repo.py",
    "backend/app/tasks/data_update_center.py",
):
    CALIBER_GATE_MAP[_source] = (*CALIBER_GATE_MAP[_source],
        "tests/test_system_read_publication_process_crash.py")
for _source in (
    "backend/app/services/campisi_attribution_service.py",
    "backend/app/schemas/campisi_attribution_read.py",
    "backend/app/services/pnl_bridge_service.py",
):
    CALIBER_GATE_MAP[_source] = (*CALIBER_GATE_MAP.get(_source, ()),
        "tests/test_campisi_formal_bridge_coverage.py")
for _source in (
    "backend/app/core_finance/product_category_pnl.py",
    "backend/app/repositories/product_category_pnl_repo.py",
    "backend/app/repositories/governance_repo.py",
    "backend/app/services/product_category_pnl_service.py",
    "backend/app/tasks/product_category_pnl.py",
):
    CALIBER_GATE_MAP[_source] = (*CALIBER_GATE_MAP[_source],
        "tests/test_product_category_read_boundary.py")
CALIBER_GATE_MAP["scripts/backend_release_suite.py"] = (
    "tests/test_backend_release_suite.py",)
for _source in (
    "backend/app/core_finance/bond_analytics/common.py",
    "backend/app/core_finance/bond_analytics/read_models.py",
    "backend/app/core_finance/pnl_bridge.py",
):
    CALIBER_GATE_MAP[_source] = (*CALIBER_GATE_MAP.get(_source, ()),
        "tests/test_yield_curve_consumer_symmetry.py")
CALIBER_GATE_MAP["backend/app/repositories/liability_analytics_repo.py"] = (
    "tests/test_repository_support_contracts.py",)
CALIBER_GATE_MAP["backend/app/services/advanced_attribution_service.py"] = (
    "tests/test_advanced_attribution_contract.py",)
CALIBER_GATE_MAP["backend/app/services/bond_analytics_service.py"] = (
    "tests/test_bond_analytics_service.py", "tests/test_advanced_attribution_contract.py")

# Self-selection uses the same map and resolver as source changes. Snapshot
# values before adding test keys so the map is never mutated during iteration.
_REGISTERED_TESTS = tuple(sorted({
    _TEST_MAPPING,
    *(test_file for test_files in CALIBER_GATE_MAP.values() for test_file in test_files),
}))
CALIBER_GATE_MAP["scripts/check_caliber_gate.py"] = _REGISTERED_TESTS
for _test_file in _REGISTERED_TESTS:
    CALIBER_GATE_MAP[_test_file] = tuple(sorted({_test_file, _TEST_MAPPING}))


class CaliberGateError(RuntimeError):
    """Raised when the PR diff cannot be determined; callers must fail closed."""


def _matches(changed_file: str, map_key: str) -> bool:
    if map_key.endswith("/"):
        return changed_file.startswith(map_key)
    return changed_file == map_key


def resolve_required_tests(
    changed_files: Iterable[str],
    gate_map: Mapping[str, Sequence[str]] | None = None,
) -> list[str]:
    """Return the sorted registered test files required by *changed_files*."""
    if gate_map is None:
        gate_map = CALIBER_GATE_MAP
    required: set[str] = set()
    for changed in changed_files:
        normalized = changed.replace("\\", "/").strip()
        if not normalized:
            continue
        for source, tests in gate_map.items():
            if _matches(normalized, source):
                required.update(tests)
    return sorted(required)


def selects_frontend_first_scope(changed_files: Iterable[str]) -> bool:
    """Whether the V1 PR needs first-scope frontend checks."""
    return any(
        _matches(changed.replace("\\", "/").strip(), source)
        for changed in changed_files
        for source in FRONTEND_FIRST_SCOPE_PATHS
    )


def selects_data_update_browser_scope(changed_files: Iterable[str]) -> bool:
    """Whether the V1 PR needs the synthetic daily-balance browser contract."""
    return any(
        _matches(changed.replace("\\", "/").strip(), source)
        for changed in changed_files
        for source in DATA_UPDATE_BROWSER_PATHS
    )


def selects_scheduler_windows_scope(changed_files: Iterable[str]) -> bool:
    """Whether the PowerShell scheduler contract needs a Windows runner."""
    return any(
        _matches(changed.replace("\\", "/").strip(), source)
        for changed in changed_files
        for source in SCHEDULER_WINDOWS_PATHS
    )


def selects_formal_release_scope(changed_files: Iterable[str]) -> bool:
    """Whether the V1 PR must run the existing backend release suite."""
    return any(
        _matches(changed.replace("\\", "/").strip(), source)
        for changed in changed_files
        for source in FORMAL_RELEASE_PATHS
    )


def list_changed_files(base_ref: str, *, cwd: Path) -> list[str]:
    """List files changed between the merge base of *base_ref* and HEAD."""
    command = ["git", "diff", "--name-only", f"{base_ref}...HEAD"]
    try:
        completed = subprocess.run(
            command,
            cwd=cwd,
            capture_output=True,
            text=True,
            encoding="utf-8",
            check=False,
        )
    except OSError as exc:
        raise CaliberGateError(
            f"unable to invoke git ({exc}); refusing to skip the caliber gate"
        ) from exc
    if completed.returncode != 0:
        stderr = completed.stderr.strip()
        raise CaliberGateError(
            f"git diff failed for base ref '{base_ref}' "
            f"(exit code {completed.returncode}): {stderr or '<no stderr>'}"
        )
    return [line.strip() for line in completed.stdout.splitlines() if line.strip()]


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Run caliber and selected formal-compute checks when the diff "
            "against --base-ref touches mapped source, test or gate files."
        )
    )
    parser.add_argument(
        "--base-ref",
        required=True,
        help="Git ref the PR diff is compared against, e.g. origin/main.",
    )
    output_mode = parser.add_mutually_exclusive_group()
    output_mode.add_argument(
        "--dry-run",
        action="store_true",
        help="Print base ref, changed files and matched tests as JSON; do not run pytest.",
    )
    output_mode.add_argument(
        "--frontend-scope",
        action="store_true",
        help="Print true/false for the bounded V1 frontend job; do not run pytest.",
    )
    output_mode.add_argument(
        "--data-update-browser-scope",
        action="store_true",
        help="Print true/false for the synthetic daily-balance browser check.",
    )
    output_mode.add_argument(
        "--scheduler-scope",
        action="store_true",
        help="Print true/false for the Windows scheduler contract checks.",
    )
    output_mode.add_argument(
        "--release-scope",
        action="store_true",
        help="Print true/false for the canonical backend release suite; do not run pytest.",
    )
    args = parser.parse_args(argv)

    try:
        changed_files = list_changed_files(args.base_ref, cwd=ROOT)
    except CaliberGateError as exc:
        print(f"caliber-gate: FAIL-CLOSED: {exc}", file=sys.stderr)
        print(
            "caliber-gate: the PR diff could not be computed, so the gate "
            "refuses to pass silently. Fix the base ref / git setup and rerun.",
            file=sys.stderr,
        )
        return 2

    matched_tests = resolve_required_tests(changed_files)

    if args.frontend_scope:
        print(str(selects_frontend_first_scope(changed_files)).lower())
        return 0

    if args.data_update_browser_scope:
        print(str(selects_data_update_browser_scope(changed_files)).lower())
        return 0

    if args.scheduler_scope:
        print(str(selects_scheduler_windows_scope(changed_files)).lower())
        return 0

    if args.release_scope:
        print(str(selects_formal_release_scope(changed_files)).lower())
        return 0

    if args.dry_run:
        print(
            json.dumps(
                {
                    "base_ref": args.base_ref,
                    "changed_files": changed_files,
                    "matched_tests": matched_tests,
                    "frontend_scope_selected": selects_frontend_first_scope(changed_files),
                    "data_update_browser_scope_selected": selects_data_update_browser_scope(changed_files),
                    "scheduler_windows_scope_selected": selects_scheduler_windows_scope(changed_files),
                    "release_scope_selected": selects_formal_release_scope(changed_files),
                },
                ensure_ascii=False,
                indent=2,
            )
        )
        return 0

    if not matched_tests:
        print(
            "caliber-gate: no mapped source, test or gate file changed vs "
            f"'{args.base_ref}'; nothing to run."
        )
        return 0

    print(
        f"caliber-gate: diff vs '{args.base_ref}' requires "
        f"{len(matched_tests)} financial check test file(s):"
    )
    for test_file in matched_tests:
        print(f"  - {test_file}")
    completed = subprocess.run(
        [sys.executable, "-m", "pytest", *matched_tests, "-q"],
        cwd=ROOT,
        check=False,
    )
    return int(completed.returncode)


if __name__ == "__main__":
    raise SystemExit(main())
