"""Path-triggered PR regressions for caliber, formal compute and balance updates.

The six caliber red-line tests (tests/test_caliber_rule_*.py) are also
unconditional members of the bounded release suite
(scripts/backend_release_suite.py, since 2026-08-12). This gate is the
targeted fast-reaction half of that double insurance: when the PR diff
touches a mapped source module, the matching test files run directly, so a
regression is attributed to the diff that caused it instead of surfacing as
a generic suite failure.

``CALIBER_GATE_MAP`` retains the six caliber rules and adds existing independent
goldens for curves, duration, KRD, PnL bridge and FX, plus balance and PnL
materialization checks. Entries follow verified test imports and their direct
production dependencies; this is not a claim of all core_finance coverage.
Only the curve-engine package has a prefix entry, so newly added implementations
there select its existing goldens without matching unrelated finance modules.
Mapped test changes run that test and the mapping guard. Gate changes run all
registered checks. No expected financial values are generated by this script.
First-scope data-update and balance-read paths also select their focused checks;
frontend changes select a separate bounded Vitest job.

Usage::

    python scripts/check_caliber_gate.py --base-ref origin/main [--dry-run]

Fail-closed: if the diff against ``--base-ref`` cannot be computed (unknown
ref, git unavailable, not a repository), the gate exits non-zero instead of
silently passing.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import subprocess
import sys
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path
from typing import TypedDict

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

_TEST_ACCOUNTING_BASIS = "tests/test_caliber_rule_accounting_basis.py"
_TEST_FORMAL_SCENARIO_GATE = "tests/test_caliber_rule_formal_scenario_gate.py"
_TEST_FX_MID_CONVERSION = "tests/test_caliber_rule_fx_mid_conversion.py"
_TEST_HAT_MAPPING = "tests/test_caliber_rule_hat_mapping.py"
_TEST_ISSUANCE_EXCLUSION = "tests/test_caliber_rule_issuance_exclusion.py"
_TEST_SUBJECT_MERGE = "tests/test_caliber_rule_subject_514_516_517_merge.py"
_TEST_CURVE = "tests/test_curve_engine_golden.py"
_TEST_DURATION = "tests/test_bond_duration_goldens.py"
_TEST_COUPON_DATES = "tests/test_bond_coupon_date_boundary.py"
_TEST_KRD = "tests/test_krd_golden.py"
_TEST_PNL_BRIDGE = "tests/test_pnl_bridge_golden.py"
_TEST_PNL_BRIDGE_DURATION = "tests/test_pnl_bridge_modified_duration.py"
_TEST_CAMPISI = "tests/test_campisi.py"
_TEST_CAMPISI_GOLDEN = "tests/test_campisi_formula_golden.py"
_TEST_CAMPISI_DECIMAL_LOCK = "tests/test_decimal_first_batch_lock.py"
_TEST_CAMPISI_SERVICE = "tests/test_campisi_attribution_service.py"
_TEST_PNL_AUDIT = "tests/test_pnl_audit_regressions.py"
_TEST_ATTRIBUTION_WORKBENCH = "tests/test_pnl_attribution_workbench_contract.py"
_TEST_ATTRIBUTION_SERVICE = "tests/test_pnl_attribution_service_explicit_numeric.py"
_TEST_FX = "tests/test_fx_rates_golden.py"
_TEST_FORMAL_FX_VALIDITY = "tests/test_formal_fx_rate_validity.py"
_TEST_FX_MATERIALIZE = "tests/test_fx_mid_materialize.py"
_TEST_BALANCE_CORE = "tests/test_balance_analysis_core.py"
_TEST_BALANCE_FLOW = "tests/test_balance_analysis_materialize_flow.py"
_TEST_BALANCE_CONSISTENCY = "tests/test_balance_analysis_snapshot_fact_consistency.py"
_TEST_PNL_FLOW = "tests/test_pnl_materialize_flow.py"
_TEST_PRODUCT_REFERENCE = "tests/test_product_category_manual_reference_flow.py"
_TEST_PRODUCT_INCREMENTAL = "tests/test_product_category_incremental_materialization.py"
_TEST_PRODUCT_API_CONTRACT = "tests/test_product_category_api_contract.py"
_TEST_PNL_INVALIDATION = "tests/test_pnl_fact_precompute_invalidation.py"
_TEST_PNL_PRECOMPUTE_STATE = "tests/test_pnl_by_business_precompute_state.py"
_TEST_PNL_INDEPENDENT_RECONCILIATION = "tests/test_pnl_independent_reconciliation.py"
_TEST_PNL_INDEPENDENT_REFERENCE_API = (
    "tests/test_pnl_overview_independent_reference_api.py"
)
_TEST_FINANCIAL_PUBLICATION = "tests/test_financial_result_publication.py"
_TEST_PNL_PAGE_LIFECYCLE = "tests/test_pnl_by_business_page_lifecycle.py"
_TEST_PNL_PUBLICATION_API = "tests/test_pnl_publication_api_contract.py"
_TEST_PNL_ADJUSTMENT_HANDOFF = "tests/test_pnl_by_business_adjustment_handoff.py"
_TEST_PNL_CANDIDATE_INSIGHTS = (
    "tests/test_pnl_by_business_candidate_insights_contract.py"
)
_TEST_PNL_INSIGHTS = "tests/test_pnl_by_business_insights_contract.py"
_TEST_GLOBAL_REFRESH = "tests/test_global_data_refresh.py"
_TEST_DATA_UPDATES = "tests/test_data_updates.py"
_TEST_SYSTEM_PUBLICATION = "tests/test_system_read_publication.py"
_TEST_WORKER_BOOTSTRAP = "tests/test_worker_bootstrap.py"
_TEST_FORMAL_JOINT_REPLAY = "tests/test_formal_compute_joint_replay.py"
_TEST_BALANCE_PUBLICATION = "tests/test_balance_analysis_overview_publication.py"
_TEST_MAPPING = "tests/test_caliber_gate_mapping.py"
_TEST_DATA_UPDATE_BALANCE_INTEGRATION = "tests/test_data_update_balance_integration.py"
_TEST_QUEUE_LAUNCHER = "tests/test_data_update_queue_launcher_logging.py"
_TEST_QUEUE_INSTALLER = "tests/test_install_data_update_queue.py"
_TEST_DATA_HEALTH = "tests/test_data_health.py"
_TEST_DATA_HEALTH_SCHTASKS_QUERY = "tests/test_data_health_schtasks_query.py"
_TEST_BALANCE_API = "tests/test_balance_analysis_api.py"

_ALL_CALIBER_TESTS = (
    _TEST_ACCOUNTING_BASIS,
    _TEST_FORMAL_SCENARIO_GATE,
    _TEST_FX_MID_CONVERSION,
    _TEST_HAT_MAPPING,
    _TEST_ISSUANCE_EXCLUSION,
    _TEST_SUBJECT_MERGE,
)

# Source file -> existing financial checks that must run when the file changes.
# Keys are repo-relative POSIX paths; a key ending with "/" is a prefix match.
CALIBER_GATE_MAP: dict[str, tuple[str, ...]] = {
    # Shared caliber framework: every caliber test starts with
    # `from backend.app.core_finance.calibers import ...`. The package
    # __init__ re-exports enums/descriptor/registry symbols used by the
    # tests (Basis/View/Resolution/ALL_CELLS, get_caliber_rule,
    # assert_canonical_callsite, CaliberCalibrationViolation), and
    # rules/__init__ side-effect-registers every bundled rule descriptor
    # (asserted by each test's *_is_registered_after_package_import case).
    "backend/app/core_finance/calibers/__init__.py": _ALL_CALIBER_TESTS,
    "backend/app/core_finance/calibers/descriptor.py": _ALL_CALIBER_TESTS,
    "backend/app/core_finance/calibers/enums.py": _ALL_CALIBER_TESTS,
    "backend/app/core_finance/calibers/registry.py": _ALL_CALIBER_TESTS,
    "backend/app/core_finance/calibers/rules/__init__.py": _ALL_CALIBER_TESTS,
    # Rule modules: each caliber test imports its own DESCRIPTOR module.
    "backend/app/core_finance/calibers/rules/accounting_basis.py": (
        _TEST_ACCOUNTING_BASIS,
    ),
    "backend/app/core_finance/calibers/rules/formal_scenario_gate.py": (
        _TEST_FORMAL_SCENARIO_GATE,
    ),
    "backend/app/core_finance/calibers/rules/fx_mid_conversion.py": (
        _TEST_FX_MID_CONVERSION,
    ),
    "backend/app/core_finance/calibers/rules/hat_mapping.py": (
        _TEST_HAT_MAPPING,
    ),
    "backend/app/core_finance/calibers/rules/issuance_exclusion.py": (
        _TEST_ISSUANCE_EXCLUSION,
    ),
    "backend/app/core_finance/calibers/rules/subject_514_516_517_merge.py": (
        _TEST_SUBJECT_MERGE,
    ),
    # Canonical modules imported by specific tests, either statically
    # (subject merge: LEDGER_PNL_ACCOUNT_PREFIXES; accounting basis:
    # derive_accounting_basis_value) or via
    # importlib.import_module(DESCRIPTOR.canonical_module) (hat mapping,
    # issuance exclusion, fx mid conversion).
    "backend/app/core_finance/config/classification_rules.py": (
        _TEST_HAT_MAPPING,
        _TEST_ISSUANCE_EXCLUSION,
        _TEST_SUBJECT_MERGE,
        _TEST_BALANCE_CORE,
        _TEST_DURATION,
        _TEST_KRD,
        _TEST_PNL_FLOW,
        _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/core_finance/field_normalization.py": (
        _TEST_ACCOUNTING_BASIS,
        _TEST_BALANCE_CORE,
        _TEST_DURATION,
        _TEST_KRD,
        _TEST_PNL_FLOW,
        _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/core_finance/fx_rates.py": (
        _TEST_FX_MID_CONVERSION,
        _TEST_FX,
        "tests/test_fx_rates.py",
        _TEST_FORMAL_FX_VALIDITY,
        _TEST_FX_MATERIALIZE,
        _TEST_BALANCE_FLOW,
        _TEST_PNL_FLOW,
    ),
    # Curve tests import bootstrapper/types/interpolation/NS directly; PnL
    # bridge consumes curve_types and interpolation from the same package.
    "backend/app/core_finance/curve_engine/": (_TEST_CURVE, _TEST_PNL_BRIDGE),
    "backend/app/core_finance/pnl_bridge.py": (
        _TEST_PNL_BRIDGE, _TEST_PNL_BRIDGE_DURATION,
        "tests/test_pnl_bridge_core.py", "tests/test_pnl_bridge_ambiguity.py",
        "tests/test_pnl_api_contract.py",
        "tests/test_campisi_dirty_input.py",
    ),
    "backend/app/services/pnl_bridge_service.py": (
        _TEST_PNL_BRIDGE, "tests/test_pnl_bridge_core.py",
        "tests/test_pnl_bridge_ambiguity.py",
        "tests/test_pnl_api_contract.py", "tests/test_campisi_dirty_input.py",
    ),
    # These numerical paths were absent from the path-trigger gate. Keep the
    # independent formulas, null semantics and service boundary checks together.
    "backend/app/core_finance/campisi.py": (
        _TEST_CAMPISI, _TEST_CAMPISI_GOLDEN, _TEST_CAMPISI_DECIMAL_LOCK, _TEST_PNL_AUDIT,
        "tests/test_attribution_daily.py",
    ),
    "backend/app/services/campisi_attribution_service.py": (
        _TEST_CAMPISI_SERVICE, _TEST_PNL_AUDIT,
        "tests/test_campisi_dirty_input.py",
    ),
    "backend/app/core_finance/pnl_attribution/workbench.py": (
        _TEST_ATTRIBUTION_WORKBENCH, _TEST_PNL_AUDIT,
    ),
    "backend/app/services/pnl_attribution_service.py": (
        _TEST_ATTRIBUTION_SERVICE, _TEST_PNL_AUDIT,
    ),
    "backend/app/core_finance/attribution_daily.py": (
        "tests/test_attribution_daily.py", _TEST_CAMPISI_GOLDEN,
    ),
    # TTM flow/snapshot alignment and the service's query-cache version are
    # exercised together by this existing synthetic repair regression.
    "backend/app/core_finance/action_attribution.py": (
        "tests/test_pnl_audit_repair.py",
    ),
    "backend/app/core_finance/credit_spread_analysis.py": (
        "backend/tests/core_finance/test_credit_spread_analysis.py",
        "tests/test_credit_spread_analysis.py",
    ),
    "backend/app/core_finance/balance_analysis_workbook.py": (
        "tests/test_balance_workbook_decimal_nan_guard.py",
    ),
    "backend/app/core_finance/balance_workbook/_utils.py": (
        "tests/test_balance_workbook_decimal_nan_guard.py",
    ),
    # Duration delegates discounting to common; KRD imports bond_duration.
    # These are numerical checks of those paths, not the whole risk tensor.
    "backend/app/core_finance/bond_duration.py": (
        _TEST_DURATION, _TEST_KRD, _TEST_COUPON_DATES, _TEST_CAMPISI_DECIMAL_LOCK,
        "tests/test_bond_duration.py",
    ),
    "backend/app/core_finance/bond_analytics/common.py": (
        "tests/test_bond_analytics_core.py",
        "tests/test_bond_analytics_engine.py",
        "tests/test_bond_duration.py",
        "tests/test_bond_four_effects.py",
        _TEST_DURATION,
        _TEST_KRD,
        _TEST_PNL_BRIDGE,
        _TEST_PNL_BRIDGE_DURATION,
        _TEST_COUPON_DATES,
        _TEST_CAMPISI_DECIMAL_LOCK,
    ),
    "backend/app/core_finance/krd.py": (_TEST_KRD, _TEST_COUPON_DATES, "tests/test_krd.py"),
    "backend/app/core_finance/credit_spread.py": ("tests/test_credit_spread.py",),
    # The date boundary test independently enumerates coupon months forward
    # and checks common, engine, KRD and Campisi entrypoints. Production common
    # obtains its backwards coupon schedule from cashflow_projection.
    "backend/app/core_finance/bond_analytics/engine.py": (
        _TEST_COUPON_DATES, "tests/test_bond_analytics_core.py",
        "tests/test_bond_analytics_engine.py",
    ),
    "backend/app/core_finance/bond_four_effects.py": (
        _TEST_COUPON_DATES, _TEST_CAMPISI_GOLDEN, _TEST_CAMPISI_DECIMAL_LOCK, _TEST_PNL_AUDIT,
        "tests/test_bond_four_effects.py",
    ),
    "backend/app/core_finance/cashflow_projection.py": (
        _TEST_COUPON_DATES, _TEST_CAMPISI_DECIMAL_LOCK,
    ),
    "backend/app/core_finance/risk_tensor.py": (_TEST_KRD,),
    "backend/app/core_finance/attribution_core.py": (_TEST_KRD,),
    "backend/app/core_finance/accounting_basis_constants.py": (
        _TEST_PNL_BRIDGE,
        _TEST_BALANCE_CORE,
        _TEST_PNL_FLOW,
    ),
    # Shared conversions must exercise consumers as well as helper contracts:
    # rate_units -> bridge/KRD; safe_decimal -> common/KRD;
    # decimal_utils -> FX and formal PnL normalization.
    "backend/app/core_finance/rate_units.py": (
        "tests/test_rate_units.py",
        "tests/test_rate_units_decimal.py",
        _TEST_CAMPISI,
        _TEST_PNL_AUDIT,
        _TEST_PNL_BRIDGE,
        _TEST_KRD,
    ),
    "backend/app/core_finance/safe_decimal.py": (
        _TEST_DURATION,
        _TEST_KRD,
        _TEST_PNL_BRIDGE,
    ),
    "backend/app/core_finance/decimal_utils.py": (
        "tests/test_decimal_utils_strict.py",
        _TEST_FX,
        _TEST_PNL_FLOW,
    ),
    # Both formal balance and PnL use the FX calendar for admissible dates.
    "backend/app/core_finance/fx_calendar.py": (
        _TEST_FX,
        "tests/test_fx_calendar.py",
        "tests/test_fx_rates.py",
        _TEST_FORMAL_FX_VALIDITY,
        _TEST_FX_MATERIALIZE,
        _TEST_BALANCE_FLOW,
        _TEST_PNL_FLOW,
    ),
    "backend/app/tasks/fx_mid_materialize.py": (
        _TEST_BALANCE_FLOW, _TEST_FX_MATERIALIZE, _TEST_FORMAL_FX_VALIDITY,
    ),
    "backend/app/repositories/adb_analysis_repo.py": (
        "tests/test_adb_snapshot_fx_fallback.py", _TEST_FORMAL_FX_VALIDITY,
    ),
    "backend/app/core_finance/balance_analysis.py": (
        _TEST_BALANCE_CORE,
        _TEST_BALANCE_FLOW,
        _TEST_BALANCE_CONSISTENCY,
        _TEST_BALANCE_API,
    ),
    "backend/app/repositories/balance_analysis_repo.py": (
        _TEST_FORMAL_FX_VALIDITY,
        _TEST_BALANCE_FLOW,
        _TEST_BALANCE_CONSISTENCY,
        _TEST_PNL_INVALIDATION,
        _TEST_BALANCE_PUBLICATION,
        _TEST_BALANCE_API,
    ),
    "backend/app/tasks/balance_analysis_materialize.py": (
        _TEST_BALANCE_FLOW,
        _TEST_BALANCE_CONSISTENCY,
        _TEST_BALANCE_PUBLICATION,
        _TEST_FORMAL_JOINT_REPLAY,
        _TEST_BALANCE_API,
    ),
    "backend/app/repositories/snapshot_repo.py": (
        _TEST_BALANCE_FLOW,
        _TEST_BALANCE_CONSISTENCY,
        "tests/test_snapshot_dq_guardrails.py",
        "tests/test_snapshot_materialize_flow.py",
    ),
    "backend/app/tasks/snapshot_materialize.py": (
        "tests/test_snapshot_dq_guardrails.py",
        "tests/test_snapshot_materialize_flow.py",
    ),
    "backend/app/core_finance/pnl.py": (_TEST_PNL_FLOW,),
    "backend/app/core_finance/pnl_constants.py": (_TEST_PNL_FLOW,),
    "backend/app/tasks/pnl_materialize.py": (
        _TEST_FORMAL_FX_VALIDITY,
        _TEST_PNL_FLOW,
        _TEST_PNL_INVALIDATION,
        _TEST_FORMAL_JOINT_REPLAY,
    ),
    "backend/app/tasks/bond_analytics_materialize.py": (
        _TEST_FORMAL_JOINT_REPLAY,
    ),
    "backend/app/tasks/risk_tensor_materialize.py": (
        _TEST_FORMAL_JOINT_REPLAY,
    ),
    # PnL fact revisions invalidate derived page state. These checks exercise
    # commit/rollback semantics and the pinned dependency revision used by the
    # precompute worker, rather than treating an old page row as current.
    "backend/app/repositories/pnl_precompute_state.py": (
        _TEST_PNL_INVALIDATION,
        _TEST_PNL_PRECOMPUTE_STATE,
    ),
    "backend/app/repositories/pnl_repo.py": (
        _TEST_FORMAL_FX_VALIDITY,
        _TEST_PNL_INVALIDATION,
        _TEST_PNL_PRECOMPUTE_STATE,
        _TEST_PNL_INDEPENDENT_RECONCILIATION,
    ),
    "backend/app/tasks/pnl_by_business_precompute.py": (
        _TEST_PNL_INVALIDATION,
        _TEST_PNL_PRECOMPUTE_STATE,
    ),
    "backend/app/services/pnl_service_by_business_support.py": (
        _TEST_PNL_PRECOMPUTE_STATE,
        _TEST_PNL_PAGE_LIFECYCLE,
    ),
    "backend/app/services/pnl_by_business_precompute_lifecycle.py": (
        _TEST_PNL_PRECOMPUTE_STATE,
        _TEST_PNL_ADJUSTMENT_HANDOFF,
        _TEST_PNL_PAGE_LIFECYCLE,
    ),
    "backend/app/services/pnl_task_dispatch.py": (
        _TEST_PNL_PAGE_LIFECYCLE,
        _TEST_PNL_PUBLICATION_API,
    ),
    "backend/app/services/pnl_by_business_adjustment_handoff.py": (
        _TEST_PNL_ADJUSTMENT_HANDOFF,
        _TEST_PNL_PAGE_LIFECYCLE,
    ),
    # Financial publication has one immutable writer/reader protocol. The page
    # lifecycle and HTTP contract checks stay attached only to their adapters.
    "backend/app/repositories/financial_result_publication_repo.py": (
        _TEST_FINANCIAL_PUBLICATION,
        _TEST_BALANCE_PUBLICATION,
        _TEST_SYSTEM_PUBLICATION,
    ),
    "backend/app/tasks/financial_result_publication.py": (
        _TEST_FINANCIAL_PUBLICATION,
        _TEST_BALANCE_PUBLICATION,
        _TEST_SYSTEM_PUBLICATION,
    ),
    "backend/app/tasks/balance_analysis_overview_publication.py": (
        _TEST_BALANCE_PUBLICATION,
    ),
    "backend/app/services/balance_analysis_publication_service.py": (
        _TEST_BALANCE_PUBLICATION,
    ),
    "backend/app/services/balance_analysis_service.py": (
        _TEST_BALANCE_PUBLICATION,
        _TEST_BALANCE_API,
    ),
    "backend/app/api/routes/balance_analysis.py": (
        _TEST_BALANCE_PUBLICATION,
        _TEST_BALANCE_API,
    ),
    "backend/app/schemas/balance_analysis.py": (
        _TEST_BALANCE_PUBLICATION,
        _TEST_BALANCE_API,
    ),
    "backend/app/governance/settings.py": (
        _TEST_BALANCE_PUBLICATION,
    ),
    "backend/app/tasks/pnl_by_business_page_publication.py": (
        _TEST_FINANCIAL_PUBLICATION,
        _TEST_PNL_PAGE_LIFECYCLE,
    ),
    "backend/app/services/pnl_by_business_page_lifecycle.py": (
        _TEST_PNL_PAGE_LIFECYCLE,
    ),
    "backend/app/services/pnl_by_business_page_readiness.py": (
        _TEST_PNL_PAGE_LIFECYCLE,
    ),
    "backend/app/services/pnl_by_business_publication_service.py": (
        _TEST_PNL_PAGE_LIFECYCLE,
        _TEST_PNL_PUBLICATION_API,
    ),
    "backend/app/services/pnl_by_business_page_dates.py": (
        _TEST_PNL_PUBLICATION_API,
    ),
    "backend/app/core_finance/pnl_by_business_insights.py": (
        _TEST_PNL_CANDIDATE_INSIGHTS,
        _TEST_PNL_INSIGHTS,
    ),
    "backend/app/services/pnl_by_business_candidate_insights.py": (
        _TEST_FINANCIAL_PUBLICATION,
        _TEST_PNL_CANDIDATE_INSIGHTS,
        _TEST_PNL_PAGE_LIFECYCLE,
    ),
    "scripts/run_global_data_refresh.py": (
        _TEST_FINANCIAL_PUBLICATION,
        _TEST_GLOBAL_REFRESH,
        _TEST_DATA_UPDATES,
        _TEST_SYSTEM_PUBLICATION,
    ),
    # Request persistence and the worker share the publication-failure boundary:
    # completed financial work must never be replayed by a publication retry.
    "backend/app/api/routes/data_updates.py": (
        _TEST_DATA_UPDATES, _TEST_DATA_UPDATE_BALANCE_INTEGRATION,
    ),
    "backend/app/services/data_update_service.py": (
        _TEST_DATA_UPDATES, _TEST_DATA_UPDATE_BALANCE_INTEGRATION,
    ),
    "backend/app/repositories/data_update_repo.py": (
        _TEST_DATA_UPDATES, _TEST_SYSTEM_PUBLICATION,
        _TEST_DATA_UPDATE_BALANCE_INTEGRATION,
    ),
    "backend/app/tasks/data_update_center.py": (
        _TEST_DATA_UPDATES, _TEST_SYSTEM_PUBLICATION,
        _TEST_DATA_UPDATE_BALANCE_INTEGRATION,
    ),
    "backend/app/tasks/system_read_publication.py": (_TEST_SYSTEM_PUBLICATION,),
    "backend/app/repositories/system_read_publication_repo.py": (_TEST_SYSTEM_PUBLICATION,),
    "backend/app/tasks/worker_bootstrap.py": (_TEST_WORKER_BOOTSTRAP,),
    "backend/app/tasks/worker_recovery.py": (_TEST_WORKER_BOOTSTRAP,),
    "backend/app/tasks/broker.py": (_TEST_WORKER_BOOTSTRAP,),
    "backend/app/tasks/pnl_by_business_resource_scope.py": (
        _TEST_FINANCIAL_PUBLICATION,
        _TEST_PNL_PRECOMPUTE_STATE,
    ),
    # Independent reconciliation keeps the numerical comparator and the
    # persisted/read API reference path covered separately.
    "backend/app/core_finance/pnl_independent_reconciliation.py": (
        _TEST_PNL_INDEPENDENT_RECONCILIATION,
    ),
    "backend/app/repositories/pnl_independent_reference_repo.py": (
        _TEST_PNL_INDEPENDENT_RECONCILIATION,
        _TEST_PNL_INDEPENDENT_REFERENCE_API,
    ),
    "backend/app/services/pnl_independent_reference_service.py": (
        _TEST_PNL_INDEPENDENT_RECONCILIATION,
        _TEST_PNL_INDEPENDENT_REFERENCE_API,
    ),
    "backend/app/services/pnl_service.py": (
        _TEST_PNL_INDEPENDENT_RECONCILIATION,
        _TEST_PNL_INDEPENDENT_REFERENCE_API,
    ),
    "backend/app/api/routes/pnl.py": (
        _TEST_PNL_INDEPENDENT_REFERENCE_API,
        _TEST_PNL_PUBLICATION_API,
    ),
    # The existing product reference starts at synthetic source workbooks,
    # runs the real materializer, and checks persisted rows plus HTTP output.
    # Annual reuse also fingerprints these production dependencies. A source,
    # schema or implementation change must exercise rebuild-versus-reuse checks.
    "backend/app/core_finance/product_category_pnl.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/config/product_category_mapping.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/core_finance/config/product_category_mapping.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/core_finance/config/product_category_contract.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/services/product_category_source_service.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/services/source_file_hash.py": (_TEST_PRODUCT_INCREMENTAL,),
    "backend/app/tasks/product_category_pnl.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/tasks/product_category_refresh_state.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/repositories/product_category_pnl_repo.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/schema_registry/duckdb/08_product_category_pnl.sql": (
        _TEST_PRODUCT_INCREMENTAL,
    ),
    "backend/app/services/product_category_pnl_service.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_API_CONTRACT,
    ),
    "backend/app/api/routes/product_category_pnl.py": (
        _TEST_PRODUCT_REFERENCE, _TEST_PRODUCT_API_CONTRACT,
    ),
    # Refresh inherits CacheBuildRunRecord; the HTTP contract also proves that
    # the OpenAPI checker notices removals from nested product response models.
    "backend/app/schemas/product_category_pnl.py": (_TEST_PRODUCT_API_CONTRACT,),
    "backend/app/schemas/materialize.py": (_TEST_PRODUCT_API_CONTRACT,),
    "scripts/api_contract_check.py": (_TEST_PRODUCT_API_CONTRACT,),
    "backend/app/core_finance/reconciliation_checks.py": (
        "tests/test_reconciliation_checks.py",
    ),
    # First-scope request, receipt, and balance read path on codex/V1.
    "backend/app/api/__init__.py": (_TEST_DATA_UPDATES, _TEST_DATA_UPDATE_BALANCE_INTEGRATION),
    "backend/app/schemas/data_updates.py": (_TEST_DATA_UPDATES, _TEST_DATA_UPDATE_BALANCE_INTEGRATION),
    "backend/app/api/routes/data_health.py": (_TEST_DATA_HEALTH, _TEST_DATA_UPDATES),
    "backend/app/services/data_health_service.py": (
        _TEST_DATA_HEALTH,
        _TEST_DATA_HEALTH_SCHTASKS_QUERY,
        _TEST_DATA_UPDATES,
    ),
    "scripts/scheduling/drain_data_updates.ps1": (_TEST_QUEUE_LAUNCHER, _TEST_QUEUE_INSTALLER),
    "scripts/scheduling/install_data_update_queue.ps1": (_TEST_QUEUE_INSTALLER,),
    _TEST_DATA_UPDATES: (_TEST_DATA_UPDATES,),
    _TEST_DATA_UPDATE_BALANCE_INTEGRATION: (_TEST_DATA_UPDATE_BALANCE_INTEGRATION,),
    _TEST_QUEUE_LAUNCHER: (_TEST_QUEUE_LAUNCHER,),
    _TEST_QUEUE_INSTALLER: (_TEST_QUEUE_INSTALLER,),
    _TEST_DATA_HEALTH_SCHTASKS_QUERY: (_TEST_DATA_HEALTH_SCHTASKS_QUERY,),
    _TEST_BALANCE_API: (_TEST_BALANCE_API,),
}

# Relevant frontend edits need the bounded page/API checks in the V1 PR job.
# Keep these paths exact where possible so unrelated features do not install npm.
FRONTEND_FIRST_SCOPE_PATHS = (
    "frontend/src/features/platform-config/",
    "frontend/src/features/balance-analysis/",
    "frontend/src/api/dataUpdatesClient.ts",
    "frontend/src/api/dataUpdatesClient.test.ts",
    "frontend/src/api/balanceAnalysisClient.ts",
    "frontend/src/api/balanceAnalysisClient.datesContract.test.ts",
    "frontend/src/api/balanceMovementClient.ts",
    "frontend/src/api/balanceMovementClient.test.ts",
    "frontend/src/api/homeSupplementalClient.ts",
    "frontend/src/api/clientContext.ts",
    "frontend/src/api/transport.ts",
    "frontend/src/api/contracts/balanceLedger.ts",
    "frontend/src/test/PlatformConfigPage.test.tsx",
    "frontend/src/test/BalanceAnalysisDateSemanticsContract.test.tsx",
    "frontend/src/test/BalanceAnalysisPage.test.tsx",
    "frontend/src/test/BalanceMovementRequestBoundary.test.tsx",
    "frontend/tests/playwright/data-update-center-balance-daily.spec.mjs",
)

DATA_UPDATE_BROWSER_PATHS = (
    "frontend/src/features/platform-config/",
    "frontend/src/api/dataUpdatesClient.ts",
    "frontend/src/api/dataUpdatesClient.test.ts",
    "frontend/src/api/balanceAnalysisClient.ts",
    "frontend/src/api/homeSupplementalClient.ts",
    "frontend/tests/playwright/data-update-center-balance-daily.spec.mjs",
)

SCHEDULER_WINDOWS_PATHS = (
    "scripts/scheduling/drain_data_updates.ps1",
    "scripts/scheduling/install_data_update_queue.ps1",
    _TEST_QUEUE_LAUNCHER,
    _TEST_QUEUE_INSTALLER,
)

# Formal calculation and release-cutoff edits still require the canonical
# bounded release suite; ordinary data-update orchestration does not.
FORMAL_RELEASE_PATHS = (
    "backend/app/core_finance/",
    "backend/app/tasks/formal_balance_pipeline.py",
    "backend/app/tasks/balance_analysis_materialize.py",
    "scripts/backend_release_suite.py",
    "docs/V3_CUTOFF_EXIT_CRITERIA.md",
)

# Read and publication boundaries share production dependencies with the
# numerical checks above. Extend those exact paths without widening prefixes.
for _source in (
    "backend/app/main.py",
    "backend/app/repositories/duckdb_read_context.py",
    "backend/app/repositories/duckdb_repo.py",
    "backend/app/repositories/cube_query_repo.py",
    "backend/app/repositories/governance_repo.py",
    "backend/app/observability/response_cache.py",
    "backend/app/services/runtime_cache.py",
    "backend/app/services/executive_service.py",
    "backend/app/services/market_home_warmup_service.py",
    "backend/app/services/market_overview_service.py",
    "backend/app/services/pnl_service.py",
    "backend/app/api/routes/system_read_publication.py",
    "backend/app/repositories/system_read_publication_repo.py",
    "backend/app/tasks/system_read_publication.py",
    "backend/app/repositories/financial_result_publication_repo.py",
    "backend/app/tasks/financial_result_publication.py",
):
    CALIBER_GATE_MAP[_source] = (*CALIBER_GATE_MAP.get(_source, ()),
        "tests/test_system_online_read_boundary.py",
        "tests/test_system_online_publication_concurrency.py")
for _source in (
    "backend/app/repositories/system_read_publication_repo.py",
    "backend/app/tasks/system_read_publication.py",
    "backend/app/repositories/financial_result_publication_repo.py",
    "backend/app/tasks/financial_result_publication.py",
    "backend/app/repositories/data_update_repo.py",
    "backend/app/tasks/data_update_center.py",
):
    CALIBER_GATE_MAP[_source] = (*CALIBER_GATE_MAP[_source],
        "tests/test_system_read_publication_process_crash.py")
for _source in (
    "backend/app/services/campisi_attribution_service.py",
    "backend/app/schemas/campisi_attribution_read.py",
    "backend/app/services/pnl_bridge_service.py",
):
    CALIBER_GATE_MAP[_source] = (*CALIBER_GATE_MAP.get(_source, ()),
        "tests/test_campisi_formal_bridge_coverage.py")
for _source in (
    "backend/app/core_finance/product_category_pnl.py",
    "backend/app/repositories/product_category_pnl_repo.py",
    "backend/app/repositories/governance_repo.py",
    "backend/app/services/product_category_pnl_service.py",
    "backend/app/tasks/product_category_pnl.py",
):
    CALIBER_GATE_MAP[_source] = (*CALIBER_GATE_MAP[_source],
        "tests/test_product_category_read_boundary.py")
CALIBER_GATE_MAP["scripts/backend_release_suite.py"] = (
    "tests/test_backend_release_suite.py",)
for _source in (
    "backend/app/core_finance/bond_analytics/common.py",
    "backend/app/core_finance/bond_analytics/read_models.py",
    "backend/app/core_finance/pnl_bridge.py",
):
    CALIBER_GATE_MAP[_source] = (*CALIBER_GATE_MAP.get(_source, ()),
        "tests/test_yield_curve_consumer_symmetry.py")
CALIBER_GATE_MAP["backend/app/repositories/liability_analytics_repo.py"] = (
    "tests/test_repository_support_contracts.py",)
CALIBER_GATE_MAP["backend/app/services/advanced_attribution_service.py"] = (
    "tests/test_advanced_attribution_contract.py",)
CALIBER_GATE_MAP["backend/app/services/bond_analytics_service.py"] = (
    "tests/test_bond_analytics_service.py", "tests/test_advanced_attribution_contract.py",
    "tests/test_pnl_audit_repair.py")

# Keep the imported regression guards tied to their exercised production files.
# Exact paths preserve the existing gate scope; appending retains every old check.
for _source, _checks in {
    "backend/app/api/routes/ledger.py": (
        "tests/test_ledger_multipart_integrity.py",
    ),
    "backend/app/services/ledger_import_service.py": (
        "tests/test_import_duplicate_fields_contract.py",
        "tests/test_ledger_multipart_integrity.py",
    ),
    "backend/app/tasks/ledger_import.py": (
        "tests/test_import_duplicate_fields_contract.py",
        "tests/test_ledger_multipart_integrity.py",
    ),
    "backend/app/tasks/bond_dv01_limit_config_import.py": (
        "tests/test_import_duplicate_fields_contract.py",
        "tests/test_bond_dv01_limit_finite_admission.py",
    ),
    "backend/app/tasks/stock_limit_price_ingest.py": (
        "tests/test_import_duplicate_fields_contract.py",
        "tests/test_stock_limit_price_duplicate_contract.py",
    ),
    "backend/app/tasks/stock_limit_price_daily_refresh.py": (
        "tests/test_import_duplicate_fields_contract.py",
        "tests/test_stock_limit_price_duplicate_contract.py",
    ),
    "backend/app/tasks/stock_factor_refresh.py": (
        "tests/test_structural_scoped_refresh.py",
    ),
    "backend/app/repositories/stock_official_disclosure_repo.py": (
        "tests/test_stock_selected_generation_context.py",
    ),
    "backend/app/services/executive_service.py": (
        "tests/test_structural_executive_read_pin.py",
    ),
    "backend/app/repositories/cashflow_projection_repo.py": (
        "tests/test_structural_repository_read_pin.py",
    ),
    "backend/app/repositories/accounting_asset_movement_repo.py": (
        "tests/test_structural_repository_read_pin.py",
    ),
    "backend/app/repositories/ledger_analytics_repo.py": (
        "tests/test_structural_repository_read_pin.py",
        "tests/test_ledger_xlsx_text_contract.py",
        "tests/test_xlsx_text_independent_review.py",
    ),
    "backend/app/services/ledger_analytics_service.py": (
        "tests/test_structural_repository_read_pin.py",
        "tests/test_ledger_xlsx_text_contract.py",
        "tests/test_xlsx_text_independent_review.py",
    ),
    "backend/app/services/adb_analysis_service.py": (
        "tests/test_structural_adb_read_pin.py",
        "tests/test_structural_generation_cache.py",
        "tests/test_adb_comparison_locf_contract.py",
        "tests/test_adb_comparison_valid_frames_contract.py",
    ),
    "backend/app/repositories/adb_analysis_repo.py": (
        "tests/test_structural_adb_read_pin.py",
    ),
    "backend/app/services/bond_analytics_service.py": (
        "tests/test_structural_generation_cache.py",
        "tests/test_structural_bond_positions.py",
    ),
    "backend/app/core_finance/bond_analytics/read_models.py": (
        "tests/test_structural_bond_positions.py",
    ),
    "backend/app/repositories/research_calendar_repo.py": (
        "tests/test_structural_calendar_read_pin.py",
    ),
    "backend/app/services/research_calendar_service.py": (
        "tests/test_structural_calendar_read_pin.py",
    ),
    "backend/app/tasks/formal_compute_runtime.py": (
        "tests/test_structural_formal_terminal_lock.py",
    ),
    "backend/app/tasks/financial_result_publication.py": (
        "tests/test_structural_publication_negative_controls.py",
    ),
    "backend/app/repositories/financial_result_publication_repo.py": (
        "tests/test_structural_publication_negative_controls.py",
    ),
    "backend/app/tasks/system_read_publication.py": (
        "tests/test_structural_publication_negative_controls.py",
    ),
    "backend/app/repositories/home_macro_release_context_repo.py": (
        "tests/test_selected_generation_context_repositories.py",
        "tests/test_selected_generation_context_api.py",
    ),
    "backend/app/services/balance_analysis_workbook_service.py": (
        "tests/test_balance_xlsx_text_contract.py",
        "tests/test_xlsx_text_independent_review.py",
    ),
    "backend/app/core_finance/balance_analysis_workbook.py": (
        "tests/test_balance_campisi_fin002_completeness.py",
        "tests/test_balance_campisi_fin002_api.py",
        "tests/test_balance_xlsx_text_contract.py",
        "tests/test_xlsx_text_independent_review.py",
    ),
    "backend/app/services/balance_analysis_service.py": (
        "tests/test_balance_campisi_fin002_api.py",
    ),
    "backend/app/tasks/pnl_by_business_precompute.py": (
        "tests/test_structural_precompute_rounding.py",
    ),
    "backend/app/services/product_category_pnl_service.py": (
        "tests/test_structural_read_consistency.py",
        "tests/test_product_category_pnl_flow.py",
    ),
    "backend/app/services/pnl_v1_cache_support.py": (
        "tests/test_structural_read_consistency.py",
    ),
    "backend/app/core_finance/qdb_gl_monthly_analysis.py": (
        "tests/test_qdb_gl_missing_average_contract.py",
        "tests/test_qdb_gl_monthly_analysis_core.py",
    ),
    "backend/app/services/pnl_service.py": (
        "tests/test_pnl_v1_source_integrity.py",
    ),
    "backend/app/services/pnl_v1_snapshot_validation.py": (
        "tests/test_pnl_v1_source_integrity.py",
        "tests/test_pnl_api_contract.py",
    ),
    "backend/app/repositories/pnl_repo.py": (
        "tests/test_pnl_v1_source_integrity.py",
    ),
    "backend/app/core_finance/macro/toolkit/scripts/credit_bond_dashboard.py": (
        "tests/test_credit_dashboard_demo_disclosure.py",
    ),
    "backend/app/services/macro_vendor_service.py": (
        "tests/test_fx_analytical_fallback_api.py",
        "tests/test_fx_analytical_fallback_lineage.py",
        "tests/test_fx_analytical_previous_observation.py",
        "tests/test_fx_selected_availability.py",
        "tests/test_fx_selected_availability_api_review.py",
        "tests/test_fx_sql_null_chain.py",
        "tests/test_fx_analytical_view_service.py",
    ),
    "backend/app/api/routes/macro_vendor.py": (
        "tests/test_fx_analytical_fallback_api.py",
        "tests/test_fx_selected_availability_api_review.py",
    ),
    "backend/app/core_finance/fx_rates.py": (
        "tests/test_fx_analytical_fallback_lineage.py",
        "tests/test_fx_analytical_view_service.py",
    ),
    "backend/app/core_finance/macro_bond_linkage.py": (
        "tests/test_macro_portfolio_truthfulness.py",
    ),
    "backend/app/repositories/macro_bond_linkage_repo.py": (
        "tests/test_macro_portfolio_truthfulness.py",
    ),
    "backend/app/services/macro_bond_linkage_service.py": (
        "tests/test_macro_portfolio_truthfulness.py",
    ),
    "backend/app/services/macro_toolkit_route_support.py": (
        "tests/test_macro_strategy_return_truthfulness.py",
    ),
    "backend/app/services/macro_toolkit_service.py": (
        "tests/test_macro_strategy_return_truthfulness.py",
    ),
    "backend/app/core_finance/macro/equity_strategies.py": (
        "tests/test_macro_strategy_return_truthfulness.py",
    ),
}.items():
    CALIBER_GATE_MAP[_source] = (*CALIBER_GATE_MAP.get(_source, ()), *_checks)

# Self-selection uses the same map and resolver as source changes. Snapshot
# values before adding test keys so the map is never mutated during iteration.
_REGISTERED_TESTS = tuple(sorted({
    _TEST_MAPPING,
    *(test_file for test_files in CALIBER_GATE_MAP.values() for test_file in test_files),
}))
CALIBER_GATE_MAP["scripts/check_caliber_gate.py"] = _REGISTERED_TESTS
for _test_file in _REGISTERED_TESTS:
    CALIBER_GATE_MAP[_test_file] = tuple(sorted({_test_file, _TEST_MAPPING}))


class CaliberGateError(RuntimeError):
    """Raised when the PR diff cannot be determined; callers must fail closed."""


def _matches(changed_file: str, map_key: str) -> bool:
    if map_key.endswith("/"):
        return changed_file.startswith(map_key)
    return changed_file == map_key


def resolve_required_tests(
    changed_files: Iterable[str],
    gate_map: Mapping[str, Sequence[str]] | None = None,
) -> list[str]:
    """Return the sorted registered test files required by *changed_files*."""
    if gate_map is None:
        gate_map = CALIBER_GATE_MAP
    required: set[str] = set()
    for changed in changed_files:
        normalized = changed.replace("\\", "/").strip()
        if not normalized:
            continue
        for source, tests in gate_map.items():
            if _matches(normalized, source):
                required.update(tests)
    return sorted(required)


def selects_frontend_first_scope(changed_files: Iterable[str]) -> bool:
    """Whether the V1 PR needs first-scope frontend checks."""
    return any(
        _matches(changed.replace("\\", "/").strip(), source)
        for changed in changed_files
        for source in FRONTEND_FIRST_SCOPE_PATHS
    )


def selects_data_update_browser_scope(changed_files: Iterable[str]) -> bool:
    """Whether the V1 PR needs the synthetic daily-balance browser contract."""
    return any(
        _matches(changed.replace("\\", "/").strip(), source)
        for changed in changed_files
        for source in DATA_UPDATE_BROWSER_PATHS
    )


def selects_scheduler_windows_scope(changed_files: Iterable[str]) -> bool:
    """Whether the PowerShell scheduler contract needs a Windows runner."""
    return any(
        _matches(changed.replace("\\", "/").strip(), source)
        for changed in changed_files
        for source in SCHEDULER_WINDOWS_PATHS
    )


def selects_formal_release_scope(changed_files: Iterable[str]) -> bool:
    """Whether the V1 PR must run the existing backend release suite."""
    return any(
        _matches(changed.replace("\\", "/").strip(), source)
        for changed in changed_files
        for source in FORMAL_RELEASE_PATHS
    )


def list_changed_files(base_ref: str, *, cwd: Path) -> list[str]:
    """List files changed between the merge base of *base_ref* and HEAD."""
    command = ["git", "diff", "--name-only", f"{base_ref}...HEAD"]
    try:
        completed = subprocess.run(
            command,
            cwd=cwd,
            capture_output=True,
            text=True,
            encoding="utf-8",
            check=False,
        )
    except OSError as exc:
        raise CaliberGateError(
            f"unable to invoke git ({exc}); refusing to skip the caliber gate"
        ) from exc
    if completed.returncode != 0:
        stderr = completed.stderr.strip()
        raise CaliberGateError(
            f"git diff failed for base ref '{base_ref}' "
            f"(exit code {completed.returncode}): {stderr or '<no stderr>'}"
        )
    return [line.strip() for line in completed.stdout.splitlines() if line.strip()]


def _pytest_worker_args(workers: int | None) -> list[str]:
    # Keep diff/scope queries stdlib-only. Reuse the bounded gate's worker
    # policy only when executing tests; this does not apply its marker filter.
    from scripts.backend_release_suite import _worker_args

    try:
        worker_args = _worker_args(workers, include_excluded_surfaces=False)
    except ValueError as exc:
        raise CaliberGateError(f"invalid worker option or PYTEST_ADDOPTS: {exc}") from exc
    if importlib.util.find_spec("xdist") is None:
        raise CaliberGateError(
            f"pytest-xdist is unavailable in {sys.executable}; install locked "
            "dev dependencies with uv sync --frozen --project backend --extra dev "
            "--python 3.11 before executing this gate"
        )
    return worker_args


class _ShadowChange(TypedDict):
    status: str
    paths: list[str]


def _list_shadow_changes(base_ref: str) -> list[_ShadowChange]:
    """Read old and new rename paths without changing the mandatory selector."""
    completed = subprocess.run(
        ["git", "diff", "--name-status", "-z", "--find-renames", f"{base_ref}...HEAD"],
        cwd=ROOT, capture_output=True, text=True, encoding="utf-8", check=False,
    )
    if completed.returncode != 0:
        raise CaliberGateError(f"shadow git diff failed: {completed.stderr.strip()}")
    tokens = completed.stdout.split("\0")
    if tokens[-1] == "":
        tokens.pop()
    changes: list[_ShadowChange] = []
    offset = 0
    while offset < len(tokens):
        status = tokens[offset]
        path_count = 2 if status.startswith(("R", "C")) else 1
        valid_status = (
            status in {"A", "M", "D", "T", "U", "X", "B"}
            or (status[:1] in {"R", "C"} and status[1:].isdigit())
        )
        if not valid_status or offset + path_count >= len(tokens):
            raise CaliberGateError("invalid shadow name-status evidence")
        paths = tokens[offset + 1:offset + 1 + path_count]
        if any(not path for path in paths):
            raise CaliberGateError("empty path in shadow name-status evidence")
        changes.append({"status": status, "paths": paths})
        offset += 1 + path_count
    return changes


def build_shadow_selection(
    changed_files: Iterable[str],
    changes: Sequence[_ShadowChange],
    *,
    evidence_error: str | None = None,
) -> dict[str, object]:
    """Suggest existing full jobs; never feed advice to the pytest command."""
    original_paths = {path.replace("\\", "/").strip() for path in changed_files}
    paths = original_paths | {
        str(path).replace("\\", "/")
        for change in changes for path in change["paths"]
    }
    mandatory = set(resolve_required_tests(original_paths))
    extra_tests = sorted(set(resolve_required_tests(paths)) - mandatory)
    jobs: set[str] = set()
    reasons: dict[str, set[str]] = {}

    def recommend(reason: str, path: str, *job_names: str) -> None:
        reasons.setdefault(reason, set()).add(path)
        jobs.update(job_names)

    shared_backend_paths = {
        "backend/app/main.py", "backend/app/api/__init__.py",
        "backend/app/repositories/duckdb_repo.py",
        "backend/app/repositories/duckdb_read_context.py",
        "backend/app/governance/settings.py",
        "backend/app/tasks/broker.py", "backend/app/tasks/worker_bootstrap.py",
        "backend/app/tasks/worker_recovery.py",
        "backend/app/repositories/financial_result_publication_repo.py",
        "backend/app/tasks/financial_result_publication.py",
    }
    backend_config_paths = {
        "pytest.ini", "_pytest_duckdb_guard.py", "backend/pyproject.toml", "backend/uv.lock",
        "scripts/check_caliber_gate.py", "scripts/backend_release_suite.py",
    }
    frontend_config_paths = {
        "frontend/package.json", "frontend/package-lock.json", "frontend/vitest.config.ts",
        "frontend/src/api/transport.ts", "frontend/src/api/clientContext.ts",
    }
    for path in sorted(paths):
        mapped = any(_matches(path, source) for source in CALIBER_GATE_MAP)
        if path in shared_backend_paths or path.startswith("backend/app/core_finance/"):
            recommend("Core finance and shared backend boundaries need all backend layers", path, "backend-full-pytest")
        if path in backend_config_paths or path == "conftest.py" or path.endswith("/conftest.py"):
            recommend("Test, dependency or gate configuration affects backend execution", path, "backend-full-pytest")
        if path.startswith(("backend/app/api/", "backend/app/schemas/", "frontend/src/api/contracts/")):
            recommend("Public contract changes need backend and frontend consumers", path,
                      "backend-full-pytest", "frontend", "api-contract")
        if path in frontend_config_paths or path.startswith("frontend/"):
            recommend("Frontend consumers need the complete existing frontend job", path, "frontend")
        if not mapped and path.startswith(("backend/", "tests/")):
            recommend("Unmapped backend paths lack a verified domain-wide selector", path, "backend-full-pytest")
        elif not mapped and path.startswith("scripts/") and path not in backend_config_paths:
            recommend("Unmapped scripts lack a verified consumer set", path,
                      "backend-full-pytest", "frontend", "api-contract")
        elif not mapped and not path.startswith(("frontend/", "backend/", "tests/", "scripts/")) and path not in backend_config_paths:
            recommend("Unmapped paths cannot establish absence of test impact", path,
                      "backend-full-pytest", "frontend", "api-contract")
    if evidence_error is not None:
        recommend("Shadow change evidence is unavailable; related layers cannot be narrowed",
                  "<change evidence unavailable>", "backend-full-pytest", "frontend", "api-contract")
    return {
        "mode": "advisory_only",
        "status": "unavailable" if evidence_error is not None else "available",
        "execution_note": "Recommendations were not executed. Mandatory test selection is unchanged.",
        "evidence_error": evidence_error,
        "mandatory_test_file_count": len(mandatory),
        "additional_registered_test_count": len(extra_tests),
        "additional_registered_test_examples": extra_tests[:5],
        "recommended_jobs": sorted(jobs),
        "reasons": [
            {"reason": reason, "path_count": len(affected), "path_examples": sorted(affected)[:3]}
            for reason, affected in sorted(reasons.items())
        ],
        "change_status_counts": {
            status: sum(str(change["status"]).startswith(status) for change in changes)
            for status in ("A", "M", "D", "R", "C")
        },
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Run caliber and selected formal-compute checks when the diff "
            "against --base-ref touches mapped source, test or gate files."
        )
    )
    parser.add_argument(
        "--base-ref",
        required=True,
        help="Git ref the PR diff is compared against, e.g. origin/main.",
    )
    parser.add_argument(
        "--workers", type=int,
        help=(
            "Pytest workers; defaults to available CPUs capped at 4. "
            "Use 1 for serial execution; an existing PYTEST_ADDOPTS worker choice is preserved."
        ),
    )
    parser.add_argument(
        "--shadow-selection", action="store_true",
        help="Add advisory full-layer recommendations to --dry-run; never change required tests.",
    )
    output_mode = parser.add_mutually_exclusive_group()
    output_mode.add_argument(
        "--dry-run",
        action="store_true",
        help="Print base ref, changed files and matched tests as JSON; do not run pytest.",
    )
    output_mode.add_argument(
        "--frontend-scope",
        action="store_true",
        help="Print true/false for the bounded V1 frontend job; do not run pytest.",
    )
    output_mode.add_argument(
        "--data-update-browser-scope",
        action="store_true",
        help="Print true/false for the synthetic daily-balance browser check.",
    )
    output_mode.add_argument(
        "--scheduler-scope",
        action="store_true",
        help="Print true/false for the Windows scheduler contract checks.",
    )
    output_mode.add_argument(
        "--release-scope",
        action="store_true",
        help="Print true/false for the canonical backend release suite; do not run pytest.",
    )
    args = parser.parse_args(argv)
    if args.workers is not None and args.workers < 1:
        parser.error("--workers must be at least 1")
    if args.shadow_selection and not args.dry_run:
        parser.error("--shadow-selection requires --dry-run")

    try:
        changed_files = list_changed_files(args.base_ref, cwd=ROOT)
    except CaliberGateError as exc:
        print(f"caliber-gate: FAIL-CLOSED: {exc}", file=sys.stderr)
        print(
            "caliber-gate: the PR diff could not be computed, so the gate "
            "refuses to pass silently. Fix the base ref / git setup and rerun.",
            file=sys.stderr,
        )
        return 2

    matched_tests = resolve_required_tests(changed_files)

    if args.frontend_scope:
        print(str(selects_frontend_first_scope(changed_files)).lower())
        return 0

    if args.data_update_browser_scope:
        print(str(selects_data_update_browser_scope(changed_files)).lower())
        return 0

    if args.scheduler_scope:
        print(str(selects_scheduler_windows_scope(changed_files)).lower())
        return 0

    if args.release_scope:
        print(str(selects_formal_release_scope(changed_files)).lower())
        return 0

    normalized_files = sorted({
        changed.replace("\\", "/").strip() for changed in changed_files
        if changed.strip()
    })
    mapped_files = [
        changed for changed in normalized_files
        if any(_matches(changed, source) for source in CALIBER_GATE_MAP)
    ]
    unmapped_files = sorted(set(normalized_files) - set(mapped_files))
    selection_scope = (
        "Registered caliber, formal-compute and balance-update dependencies; "
        "not a complete backend or repository impact selector."
    )
    selection_note = (
        "Unmapped paths are not selected by this gate. Other jobs may test them; "
        "unmapped does not mean untested or verified. Selection is not an execution result."
    )

    if args.dry_run:
        shadow_fields: dict[str, object] = {}
        if args.shadow_selection:
            try:
                shadow_changes = _list_shadow_changes(args.base_ref)
                shadow = build_shadow_selection(changed_files, shadow_changes)
            except (CaliberGateError, OSError) as exc:
                shadow = build_shadow_selection(changed_files, (), evidence_error=str(exc))
            shadow_fields["shadow_selection"] = shadow
        print(
            json.dumps(
                {
                    "base_ref": args.base_ref,
                    "changed_files": changed_files,
                    "matched_tests": matched_tests,
                    "selection_scope": selection_scope,
                    "selection_note": selection_note,
                    "mapped_files": mapped_files,
                    "unmapped_files": unmapped_files,
                    "changed_file_count": len(normalized_files),
                    "mapped_file_count": len(mapped_files),
                    "unmapped_file_count": len(unmapped_files),
                    "frontend_scope_selected": selects_frontend_first_scope(changed_files),
                    "data_update_browser_scope_selected": selects_data_update_browser_scope(changed_files),
                    "scheduler_windows_scope_selected": selects_scheduler_windows_scope(changed_files),
                    "release_scope_selected": selects_formal_release_scope(changed_files),
                    **shadow_fields,
                },
                ensure_ascii=False,
                indent=2,
            )
        )
        return 0

    print(
        f"caliber-gate: {len(mapped_files)} mapped changed path(s), "
        f"{len(unmapped_files)} unmapped path(s), {len(matched_tests)} selected test file(s)."
    )
    print(f"caliber-gate: {selection_note} Use --dry-run for the complete path lists.")

    if not matched_tests:
        print(
            "caliber-gate: no mapped source, test or gate file changed vs "
            f"'{args.base_ref}'; nothing to run."
        )
        return 0

    print(
        f"caliber-gate: diff vs '{args.base_ref}' requires "
        f"{len(matched_tests)} financial check test file(s):"
    )
    for test_file in matched_tests:
        print(f"  - {test_file}")
    try:
        worker_args = _pytest_worker_args(args.workers)
    except CaliberGateError as exc:
        print(f"caliber-gate: FAIL-CLOSED: {exc}", file=sys.stderr)
        return 2
    completed = subprocess.run(
        [sys.executable, "-m", "pytest", *matched_tests, "-q", *worker_args],
        cwd=ROOT,
        check=False,
    )
    return int(completed.returncode)


if __name__ == "__main__":
    raise SystemExit(main())
