@echo off
setlocal

set SCRIPT_DIR=%~dp0
for %%I in ("%SCRIPT_DIR%..") do set ROOT=%%~fI

cd /d "%ROOT%"

echo [MOSS Agent] Repo root: %ROOT%

set MOSS_AGENT_ENABLED=true
set MOSS_AGENT_PROVIDER=hermes
set MOSS_AGENT_HERMES_HOME=/home/hermes/.hermes
set MOSS_AGENT_HERMES_TRANSPORT=cli
set MOSS_AGENT_HERMES_BRIDGE_URL=http://127.0.0.1:7891
set MOSS_AGENT_HERMES_MODEL=gpt-5.4-mini
set MOSS_AGENT_HERMES_TOOLSETS=file
set MOSS_DEV_API_SCRIPT=dev-agent-api.ps1
set MOSS_SKIP_STARTUP_STORAGE_MIGRATIONS=1

echo [MOSS Agent] MOSS_AGENT_ENABLED=%MOSS_AGENT_ENABLED%
echo [MOSS Agent] MOSS_AGENT_PROVIDER=%MOSS_AGENT_PROVIDER%
echo [MOSS Agent] MOSS_AGENT_HERMES_HOME=%MOSS_AGENT_HERMES_HOME%
echo [MOSS Agent] MOSS_AGENT_HERMES_TRANSPORT=%MOSS_AGENT_HERMES_TRANSPORT%
echo [MOSS Agent] MOSS_AGENT_HERMES_BRIDGE_URL=%MOSS_AGENT_HERMES_BRIDGE_URL%
echo [MOSS Agent] MOSS_AGENT_HERMES_TOOLSETS=%MOSS_AGENT_HERMES_TOOLSETS%
echo [MOSS Agent] MOSS_DEV_API_SCRIPT=%MOSS_DEV_API_SCRIPT%
echo [MOSS Agent] MOSS_SKIP_STARTUP_STORAGE_MIGRATIONS=%MOSS_SKIP_STARTUP_STORAGE_MIGRATIONS%

powershell -NoProfile -ExecutionPolicy Bypass -File "%ROOT%\scripts\dev-api.ps1"

endlocal
