create table if not exists source_version_registry (
  source_name text not null,
  source_version text not null,
  created_at timestamptz default now()
);

create table if not exists rule_version_registry (
  rule_name text not null,
  rule_version text not null,
  created_at timestamptz default now()
);

create table if not exists cache_manifest (
  row_id bigint generated by default as identity primary key,
  cache_key text not null,
  source_version text not null,
  vendor_version text,
  rule_version text not null,
  payload_json text not null default '{}',
  created_at timestamptz default now()
);

create table if not exists cache_build_run (
  row_id bigint generated by default as identity primary key,
  run_id text not null,
  job_name text not null,
  status text not null,
  cache_key text not null,
  lock text not null,
  source_version text,
  vendor_version text,
  rule_version text,
  started_at text,
  finished_at text,
  error_message text,
  payload_json text not null default '{}',
  created_at timestamptz default now()
);

alter table if exists cache_manifest
  add column if not exists row_id bigint;
alter table if exists cache_manifest
  add column if not exists vendor_version text;
alter table if exists cache_manifest
  add column if not exists payload_json text not null default '{}';

alter table if exists cache_build_run
  add column if not exists row_id bigint;
alter table if exists cache_build_run
  add column if not exists source_version text;
alter table if exists cache_build_run
  add column if not exists vendor_version text;
alter table if exists cache_build_run
  add column if not exists rule_version text;
alter table if exists cache_build_run
  add column if not exists started_at text;
alter table if exists cache_build_run
  add column if not exists finished_at text;
alter table if exists cache_build_run
  add column if not exists error_message text;
alter table if exists cache_build_run
  add column if not exists payload_json text not null default '{}';
