import { designTokens } from "./designSystem";

/**
 * Legacy shell aliases map design scales to existing consumer keys.
 * IB light restyle (2026-06-12): flat paper canvas, flat navy rail, 2px radius.
 */
export const shellTokens = {
  colorBgApp: "#f4f3f0",
  colorBgSurface: "#ffffff",
  colorBgCanvas: "#ffffff",
  railBg: "#10161f",
  railBorder: "#0a0f16",
  railNavActiveBg: "#1a2230",
  railSurfaceTint: "transparent",
  railBrandText: "#f5f6f8",
  railTextOnNavActive: "#f5f6f8",
  railTextNavIdle: "#9aa3b0",
  railTextSupportIdle: "#9aa3b0",
  railTextSectionIdle: "#6b7480",
  railIconBorderActive: "#c9a85c",
  railIconFgActive: "#f5f6f8",
  railIconFgIdle: "#9aa3b0",
  railCountFgActive: "#6b7480",
  railCountFgIdle: "#6b7480",
  readinessBadgePlaceholderBg: "transparent",
  readinessBadgePlaceholderFg: designTokens.color.neutral[700],
  readinessBadgePlaceholderBorder: "#e2e0da",
  colorBgMuted: "#f7f6f3",
  colorBgSuccessSoft: designTokens.color.success[50],
  colorBgWarningSoft: designTokens.color.warning[50],
  colorBgDangerSoft: designTokens.color.danger[50],
  colorBorder: "#e2e0da",
  colorBorderSoft: "#e2e0da",
  colorBorderStrong: "#16191d",
  colorBorderWarning: designTokens.color.warning[200],
  colorTextPrimary: "#16191d",
  colorTextSecondary: "#5c6370",
  colorTextMuted: "#8a8f98",
  colorTextWarning: designTokens.color.warning[700],
  colorAccent: "#14366b",
  colorAccentSoft: "#eef2f8",
  colorSuccess: "#1f7a4d",
  colorWarning: designTokens.color.warning[500],
  colorDanger: "#b42318",
  colorInfo: designTokens.color.info[500],
  shadowPanel: "0 1px 2px rgba(16, 24, 29, 0.05)",
  shadowCard: "0 1px 2px rgba(16, 24, 29, 0.05)",
  shadowRail: "none",
  appBackdrop: "#f4f3f0",
  radiusPanel: 2,
  radiusCard: 2,
  railMarkGlow: "transparent",
  terminalBarBg: "#ffffff",
  terminalBarBorder: "#e2e0da",
  marketPulseBg: "#ffffff",
  marketPulseBorder: "#e2e0da",
  canvasPaperBg: "#ffffff",
  canvasPaperShade: "transparent",
} as const;
